<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
    <ProjectReference Include="../BusinessOS.Modules.Companies.Domain/BusinessOS.Modules.Companies.Domain.csproj" />
    <ProjectReference Include="../BusinessOS.Modules.Companies.Application/BusinessOS.Modules.Companies.Application.csproj" />
  </ItemGroup>
</Project>
