// <auto-generated />
using System;
using BusinessOS.Modules.Companies.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessOS.Modules.Companies.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CompaniesDbContext))]
    [Migration("20260801120905_AddActiveCompanyTaxIdUniqueness")]
    partial class AddActiveCompanyTaxIdUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("BusinessOS.Modules.Companies.Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("base_currency");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultTimeZone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_time_zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("legal_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TaxIdentificationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_identification_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_companies_is_deleted");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_companies_organization_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_companies_status");

                    b.HasIndex("OrganizationId", "IsDeleted")
                        .HasDatabaseName("ix_companies_organization_id_is_deleted");

                    b.HasIndex("OrganizationId", "TaxIdentificationNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_companies_organization_tax_id_active")
                        .HasFilter("is_deleted = 0 AND tax_identification_number IS NOT NULL");

                    b.ToTable("companies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
