using BusinessOS.BuildingBlocks.Domain.Ids;
using BusinessOS.Modules.Budgeting.Domain;
using Microsoft.EntityFrameworkCore;

namespace BusinessOS.Modules.Budgeting.Infrastructure.Persistence;

public sealed class BudgetingDbContext(DbContextOptions<BudgetingDbContext> options) : DbContext(options)
{
    public DbSet<Budget> Budgets => Set<Budget>();
    public DbSet<BudgetVersion> BudgetVersions => Set<BudgetVersion>();
    public DbSet<BudgetLine> BudgetLines => Set<BudgetLine>();
    public DbSet<ActualCost> ActualCosts => Set<ActualCost>();
    public DbSet<ForecastCost> ForecastCosts => Set<ForecastCost>();
    public DbSet<SupplierInvoice> SupplierInvoices => Set<SupplierInvoice>();
    protected override void OnModelCreating(ModelBuilder b)
    {
        var budget = b.Entity<Budget>(); budget.ToTable("budgets"); budget.HasKey(x => x.Id); budget.Property(x => x.Id).HasConversion(x => x.Value, x => new(x)).HasColumnName("id"); budget.Property(x => x.ProjectId).HasConversion(x => x.Value, x => new(x)).HasColumnName("business_project_id"); budget.Property(x => x.Name).HasMaxLength(256).HasColumnName("name"); budget.Property(x => x.NormalizedName).HasMaxLength(256).HasColumnName("normalized_name"); budget.Property(x => x.Status).HasConversion<string>().HasColumnName("status"); budget.Property(x => x.CreatedAtUtc).HasColumnName("created_at_utc"); budget.Property(x => x.UpdatedAtUtc).HasColumnName("updated_at_utc"); budget.Property(x => x.Version).IsConcurrencyToken().HasColumnName("version"); budget.Property(x => x.ArchivedAtUtc).HasColumnName("archived_at_utc"); budget.HasIndex(x => x.ProjectId); budget.HasIndex(x => new { x.ProjectId, x.NormalizedName }).IsUnique().HasFilter("archived_at_utc IS NULL");
        var version = b.Entity<BudgetVersion>(); version.ToTable("budget_versions"); version.HasKey(x => x.Id); version.Property(x => x.Id).HasConversion(x => x.Value, x => new(x)).HasColumnName("id"); version.Property(x => x.BudgetId).HasConversion(x => x.Value, x => new(x)).HasColumnName("budget_id"); version.Property(x => x.Number).HasColumnName("number"); version.Property(x => x.CreatedAtUtc).HasColumnName("created_at_utc"); version.Property(x => x.Note).HasMaxLength(1000).HasColumnName("note"); version.HasIndex(x => x.BudgetId); version.HasIndex(x => new { x.BudgetId, x.Number }).IsUnique(); version.HasOne<Budget>().WithMany().HasForeignKey(x => x.BudgetId).OnDelete(DeleteBehavior.Cascade);
        var line = b.Entity<BudgetLine>(); line.ToTable("budget_lines"); line.HasKey(x => x.Id); line.Property(x => x.Id).HasColumnName("id"); line.Property(x => x.VersionId).HasConversion(x => x.Value, x => new(x)).HasColumnName("budget_version_id"); line.Property(x => x.Kind).HasConversion<string>().HasColumnName("kind"); line.Property(x => x.Name).HasMaxLength(256).HasColumnName("name"); line.ComplexProperty(x => x.Amount, money => { money.Property(x => x.Amount).HasColumnType("TEXT").HasColumnName("amount"); money.Property(x => x.Currency).HasConversion(x => x.Value, x => new(x)).HasMaxLength(3).HasColumnName("currency"); }); line.Property(x => x.SortOrder).HasColumnName("sort_order"); line.Property(x => x.Note).HasMaxLength(1000).HasColumnName("note"); line.HasIndex(x => x.VersionId); line.HasOne<BudgetVersion>().WithMany().HasForeignKey(x => x.VersionId).OnDelete(DeleteBehavior.Cascade);
        var cost = b.Entity<ActualCost>(); cost.ToTable("actual_costs"); cost.HasKey(x => x.Id); cost.Property(x => x.Id).HasConversion(x => x.Value, x => new(x)).HasColumnName("id"); cost.Property(x => x.ProjectId).HasConversion(x => x.Value, x => new(x)).HasColumnName("business_project_id"); cost.Property(x => x.Kind).HasConversion<string>().HasColumnName("kind"); cost.Property(x => x.Name).HasMaxLength(256).HasColumnName("name"); cost.Property(x => x.IncurredOn).HasColumnName("incurred_on"); cost.ComplexProperty(x => x.Amount, money => { money.Property(x => x.Amount).HasColumnType("TEXT").HasColumnName("amount"); money.Property(x => x.Currency).HasConversion(x => x.Value, x => new(x)).HasMaxLength(3).HasColumnName("currency"); }); cost.Property(x => x.Note).HasMaxLength(1000).HasColumnName("note"); cost.Property(x => x.CreatedAtUtc).HasColumnName("created_at_utc"); cost.Property(x => x.UpdatedAtUtc).HasColumnName("updated_at_utc"); cost.Property(x => x.Version).IsConcurrencyToken().HasColumnName("version"); cost.Property(x => x.ArchivedAtUtc).HasColumnName("archived_at_utc"); cost.HasIndex(x => x.ProjectId); cost.HasIndex(x => new { x.ProjectId, x.IncurredOn });
        var forecast = b.Entity<ForecastCost>(); forecast.ToTable("forecast_costs"); forecast.HasKey(x => x.Id); forecast.Property(x => x.Id).HasConversion(x => x.Value, x => new(x)).HasColumnName("id"); forecast.Property(x => x.ProjectId).HasConversion(x => x.Value, x => new(x)).HasColumnName("business_project_id"); forecast.Property(x => x.Kind).HasConversion<string>().HasColumnName("kind"); forecast.Property(x => x.Name).HasMaxLength(256).HasColumnName("name"); forecast.Property(x => x.ExpectedOn).HasColumnName("expected_on"); forecast.ComplexProperty(x => x.Money, money => { money.Property(x => x.Amount).HasColumnType("TEXT").HasColumnName("amount"); money.Property(x => x.Currency).HasConversion(x => x.Value, x => new(x)).HasMaxLength(3).HasColumnName("currency"); }); forecast.Property(x => x.Note).HasMaxLength(1000).HasColumnName("note"); forecast.Property(x => x.CreatedAtUtc).HasColumnName("created_at_utc"); forecast.Property(x => x.UpdatedAtUtc).HasColumnName("updated_at_utc"); forecast.Property(x => x.Version).IsConcurrencyToken().HasColumnName("version"); forecast.Property(x => x.ArchivedAtUtc).HasColumnName("archived_at_utc"); forecast.HasIndex(x => x.ProjectId); forecast.HasIndex(x => new { x.ProjectId, x.ExpectedOn });
        var invoice = b.Entity<SupplierInvoice>(); invoice.ToTable("supplier_invoices", table => table.HasCheckConstraint("CK_supplier_invoices_posting_pair", "(posted_actual_cost_id IS NULL AND posted_at_utc IS NULL) OR (posted_actual_cost_id IS NOT NULL AND posted_at_utc IS NOT NULL)")); invoice.HasKey(x => x.Id); invoice.Property(x => x.Id).HasConversion(x => x.Value, x => new(x)).HasColumnName("id"); invoice.Property(x => x.ProjectId).HasConversion(x => x.Value, x => new(x)).HasColumnName("business_project_id"); invoice.Property(x => x.SupplierName).HasMaxLength(256).HasColumnName("supplier_name"); invoice.Property(x => x.SupplierKey).HasMaxLength(256).HasColumnName("supplier_key"); invoice.Property(x => x.InvoiceNumber).HasMaxLength(100).HasColumnName("invoice_number"); invoice.Property(x => x.InvoiceNumberKey).HasMaxLength(100).HasColumnName("invoice_number_key"); invoice.Property(x => x.InvoiceDate).HasColumnName("invoice_date"); invoice.Property(x => x.DueDate).HasColumnName("due_date"); invoice.ComplexProperty(x => x.Amount, money => { money.Property(x => x.Amount).HasColumnType("TEXT").HasColumnName("amount"); money.Property(x => x.Currency).HasConversion(x => x.Value, x => new(x)).HasMaxLength(3).HasColumnName("currency"); }); invoice.Property(x => x.Note).HasMaxLength(1000).HasColumnName("note"); invoice.Property(x => x.CreatedAtUtc).HasColumnName("created_at_utc"); invoice.Property(x => x.UpdatedAtUtc).HasColumnName("updated_at_utc"); invoice.Property(x => x.Version).IsConcurrencyToken().HasColumnName("version"); invoice.Property(x => x.ArchivedAtUtc).HasColumnName("archived_at_utc"); invoice.Property(x => x.PostedActualCostId).HasConversion(x => x.HasValue ? x.Value.Value : (Guid?)null, x => x.HasValue ? new ActualCostId(x.Value) : null).HasColumnName("posted_actual_cost_id"); invoice.Property(x => x.PostedAtUtc).HasColumnName("posted_at_utc"); invoice.HasIndex(x => x.PostedActualCostId).IsUnique().HasFilter("posted_actual_cost_id IS NOT NULL").HasDatabaseName("IX_supplier_invoices_posted_actual_cost_id"); invoice.HasOne<ActualCost>().WithMany().HasForeignKey(x => x.PostedActualCostId).OnDelete(DeleteBehavior.Restrict); invoice.HasIndex(x => x.ProjectId); invoice.HasIndex(x => new { x.ProjectId, x.DueDate }); invoice.HasIndex(x => new { x.ProjectId, x.SupplierKey, x.InvoiceNumberKey }).IsUnique();
    }
}
