[CmdletBinding()]
param([Parameter(Mandatory)][string]$Repository,[int]$PullRequest,[string]$CommitSha,[string]$OutputDirectory='artifacts/github-audit',[string]$ApiBaseUrl='https://api.github.com',[Security.SecureString]$Token,[string]$FixtureRoot,[switch]$Diagnostic)
$ErrorActionPreference='Stop';$codes=@{Argument=2;NotFound=10;JobFailure=20;ArtifactMissing=30;ArtifactExpired=34;ManifestInvalid=35;SummaryInvalid=32;TreeMismatch=40;Transport=50};$exitCode=0;$errorCode='OK';$transportStatus='NOT_STARTED';$root=(Resolve-Path "$PSScriptRoot/..").Path;$out=Join-Path $root $OutputDirectory;New-Item -ItemType Directory -Force $out|Out-Null;Import-Module "$PSScriptRoot/BusinessOS.CiEvidence.psm1" -Force
function Fail([int]$Code,[string]$Name,[string]$Message){throw [Exception]::new("$Code|$Name|$Message")}
function Get-Paged([string]$Uri,[string]$Property){$all=@();$page=1;do{$separator=if($Uri.Contains('?')){'&'}else{'?'};$response=Invoke-RestMethod "$Uri${separator}per_page=100&page=$page" -Headers $script:headers;$items=@($response.$Property);$all+=$items;$page++}while($items.Count-eq 100);return $all}
function Get-Tree([string]$Sha){(Invoke-RestMethod "$ApiBaseUrl/repos/$Repository/git/commits/$Sha" -Headers $script:headers).tree.sha}
function Expand-SafeZip([string]$Zip,[string]$Destination){
 Add-Type -AssemblyName System.IO.Compression.FileSystem
 $archive=[IO.Compression.ZipFile]::OpenRead($Zip)
 try{
  $entries=@($archive.Entries);if($entries.Count-gt 2048){Fail $codes.ManifestInvalid 'ZIP_LIMIT' 'Entry count exceeds 2048'}
  $rootFull=[IO.Path]::GetFullPath($Destination)+[IO.Path]::DirectorySeparatorChar
  $seen=[Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase);$files=[Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase);$directories=[Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase);[long]$total=0
  foreach($entry in $entries){
   $name=$entry.FullName.Replace('\','/').TrimEnd('/');$segments=@($name-split'/')
   $target=[IO.Path]::GetFullPath((Join-Path $Destination $name))
   $portableAbsolute=$name.StartsWith('/')-or$name.StartsWith('//')-or$name-match'^[A-Za-z]:/'
   if([string]::IsNullOrWhiteSpace($name)-or$portableAbsolute-or[IO.Path]::IsPathRooted($entry.FullName)-or$segments-contains'..'-or-not$target.StartsWith($rootFull)-or-not$seen.Add($name)){Fail $codes.ManifestInvalid 'ZIP_PATH' $entry.FullName}
   if($entry.Length-gt 67108864){Fail $codes.ManifestInvalid 'ZIP_LIMIT' "Entry too large: $name"};$total+=$entry.Length;if($total-gt 268435456){Fail $codes.ManifestInvalid 'ZIP_LIMIT' 'Total uncompressed size exceeds 256 MiB'}
   $isDirectory=[string]::IsNullOrEmpty($entry.Name);if($isDirectory){if($files.Contains($name)){Fail $codes.ManifestInvalid 'ZIP_COLLISION' $name};$directories.Add($name)|Out-Null}else{if($directories.Contains($name)){Fail $codes.ManifestInvalid 'ZIP_COLLISION' $name};$files.Add($name)|Out-Null}
   for($i=1;$i-lt$segments.Count;$i++){$parent=($segments[0..($i-1)]-join'/');if($files.Contains($parent)){Fail $codes.ManifestInvalid 'ZIP_COLLISION' $name};$directories.Add($parent)|Out-Null}
  }
  if(Test-Path $Destination){Remove-Item $Destination -Recurse -Force};New-Item -ItemType Directory -Force $Destination|Out-Null
  foreach($entry in $entries){$target=Join-Path $Destination $entry.FullName;if([string]::IsNullOrEmpty($entry.Name)){New-Item -ItemType Directory -Force $target|Out-Null}else{New-Item -ItemType Directory -Force (Split-Path $target)|Out-Null;$input=$entry.Open();$output=[IO.File]::Create($target);try{$input.CopyTo($output)}finally{$input.Dispose();$output.Dispose()}}}
 }finally{$archive.Dispose()}
}
try{
 if(([bool]$PullRequest)-eq(-not[string]::IsNullOrWhiteSpace($CommitSha))){Fail $codes.Argument 'INVALID_ARGUMENTS' 'Specify exactly one of -PullRequest or -CommitSha'}
 $localSha=(&git -C $root rev-parse HEAD).Trim();$localTree=(&git -C $root show -s --format=%T HEAD).Trim();$isFixture=[bool]$FixtureRoot
 if($isFixture){$fixture=(Resolve-Path $FixtureRoot).Path;$input=Get-Content (Join-Path $fixture 'audit-input.json') -Raw|ConvertFrom-Json;if($input.localCommitSha){$localSha=$input.localCommitSha}else{$localSha=$input.remoteHeadSha};if($input.localTreeSha){$localTree=$input.localTreeSha}else{$localTree=$input.remoteHeadTreeSha};$headSha=$input.remoteHeadSha;$headTree=$input.remoteHeadTreeSha;$mergeSha=$input.remoteMergeSha;$mergeTree=$input.remoteMergeTreeSha;$runs=@($input.runs);if(-not$runs){$runs=@([pscustomobject]@{id=100;name='ci';head_sha=$headSha;event='pull_request';status='completed';created_at='2026-01-01T00:00:00Z';run_number=1;run_attempt=$input.runAttempt;head_branch='fixture';updated_at='2026-01-01T00:01:00Z';conclusion='success';jobs=$input.jobs;artifacts=$input.artifacts})};$transportStatus='FIXTURE'
 }else{$plain=if($Token){[Net.NetworkCredential]::new('',$Token).Password}elseif($env:GITHUB_TOKEN){$env:GITHUB_TOKEN}elseif($env:GH_TOKEN){$env:GH_TOKEN}else{$null};$script:headers=@{Accept='application/vnd.github+json';'X-GitHub-Api-Version'='2022-11-28';'User-Agent'='BusinessOS-CI-Auditor'};if($plain){$script:headers.Authorization="Bearer $plain"};if($PullRequest){$pr=Invoke-RestMethod "$ApiBaseUrl/repos/$Repository/pulls/$PullRequest" -Headers $script:headers;$headSha=$pr.head.sha;$headRepository=$pr.head.repo.full_name;$mergeSha=$pr.merge_commit_sha}else{$headSha=$CommitSha;$headRepository=$Repository;$mergeSha=$CommitSha};$headTree=Get-Tree $headSha;$mergeTree=Get-Tree $mergeSha;$runs=Get-Paged "$ApiBaseUrl/repos/$Repository/actions/runs?head_sha=$headSha" workflow_runs;$transportStatus='REST_OK'}
 $expectedEvent=if($PullRequest){'pull_request'}else{$null};$candidates=@($runs|Where-Object{$_.name-eq'ci'-and$_.head_sha-eq$headSha-and$_.status-eq'completed'-and(-not$expectedEvent-or$_.event-eq$expectedEvent)}|Sort-Object @{e={[DateTimeOffset]$_.created_at}},@{e={$_.run_number}},@{e={$_.run_attempt}} -Descending);if($candidates.Count-eq 0){Fail $codes.NotFound 'RUN_NOT_FOUND' 'No completed matching ci run'};$run=$candidates[0]
 if($run.conclusion-ne'success'){Fail $codes.JobFailure 'WORKFLOW_NOT_SUCCESS' "conclusion=$($run.conclusion)"}
 if($isFixture){$jobs=@($run.jobs);$artifacts=@($run.artifacts)}else{$jobs=Get-Paged "$ApiBaseUrl/repos/$Repository/actions/runs/$($run.id)/jobs" jobs;$artifacts=Get-Paged "$ApiBaseUrl/repos/$Repository/actions/runs/$($run.id)/artifacts" artifacts}
 foreach($requiredJob in 'cross-platform','windows','required-gates'){$matches=@($jobs|Where-Object name -eq $requiredJob);if($matches.Count-ne 1-or$matches[0].conclusion-ne'success'){Fail $codes.JobFailure 'JOB_NOT_SUCCESS' "$requiredJob count=$($matches.Count) conclusion=$($matches[0].conclusion)"}}
 $expectedNames=@("businessos-cross-platform-$($run.id)-$($run.run_attempt)","businessos-windows-$($run.id)-$($run.run_attempt)");$validated=@();foreach($name in $expectedNames){$matches=@($artifacts|Where-Object name -eq $name);if($matches.Count-ne 1){Fail $codes.ArtifactMissing 'ARTIFACT_MISSING' $name};$artifact=$matches[0];if($artifact.expired-eq$true){Fail $codes.ArtifactExpired 'ARTIFACT_EXPIRED' $name};$zip=Join-Path $out "$name.zip";if($isFixture){$source=Join-Path $fixture ([string]$artifact.path);if(-not(Test-Path $source)){Fail $codes.ArtifactMissing 'ARTIFACT_SOURCE_MISSING' $source};if(Test-Path $zip){Remove-Item $zip -Force};if($artifact.zipPath){Copy-Item -LiteralPath (Join-Path $fixture ([string]$artifact.zipPath)) -Destination $zip}else{Compress-Archive -Path "$source/*" -DestinationPath $zip}}else{Invoke-WebRequest -Uri $artifact.archive_download_url -Headers $script:headers -OutFile $zip -MaximumRedirection 10};$extract=Join-Path $out "extracted/$name";Expand-SafeZip $zip $extract;$manifestPath=Join-Path $extract 'manifest.json';$summaryPath=Join-Path $extract 'summary.json';if(-not(Test-Path $manifestPath)){Fail $codes.ManifestInvalid 'MANIFEST_MISSING' $name};if(-not(Test-Path $summaryPath)){Fail $codes.SummaryInvalid 'SUMMARY_MISSING' $name};try{$manifest=Read-BusinessOSManifest -Root $extract -Path $manifestPath}catch{Fail $codes.ManifestInvalid 'MANIFEST_INVALID' $_.Exception.Message};try{$summary=Get-Content $summaryPath -Raw|ConvertFrom-Json -Depth 30;Test-BusinessOSCiEvidence $summary|Out-Null
 $expectedGate=if($name-like'businessos-cross-platform-*'){'cross-platform'}else{'windows'}
 if($summary.gateName-ne$expectedGate-or$summary.jobKey-ne$expectedGate){throw 'Artifact gate/jobKey binding mismatch'}
 if($summary.repository-ne$Repository-or$summary.workflowName-ne'ci'-or$summary.eventName-ne$run.event){throw 'Repository/workflow/event binding mismatch'}
 if([long]$summary.runId-ne[long]$run.id-or[int]$summary.runAttempt-ne[int]$run.run_attempt){throw 'Run identity binding mismatch'}
 if($PullRequest-and([int]$summary.pullRequestNumber-ne$PullRequest-or$summary.pullRequestHeadSha-ne$headSha-or$summary.pullRequestMergeSha-ne$mergeSha)){throw 'Pull request binding mismatch'}
 if($summary.checkoutKind-eq'local'){throw 'Local checkout is forbidden in Actions evidence'}
 if($summary.checkoutKind-eq'pull-request-merge'-and($summary.commitSha-ne$mergeSha-or$summary.commitTreeSha-ne$mergeTree)){throw 'Merge checkout binding mismatch'}
 if($summary.checkoutKind-eq'branch-head'-and($summary.commitSha-ne$run.head_sha-or$summary.commitTreeSha-ne$headTree)){throw 'Branch checkout binding mismatch'}
 }catch{Fail $codes.SummaryInvalid 'SUMMARY_INVALID' $_.Exception.Message};$validated+=$name}
 $commitMatch=$localSha-eq$headSha;$treeMatch=$localTree-eq$headTree;if(-not$treeMatch){Fail $codes.TreeMismatch 'TREE_MISMATCH' 'Remote head tree differs from local tree'};$result=[ordered]@{status='PASS';errorCode='OK';transportStatus=$transportStatus;repository=$Repository;pullRequest=$PullRequest;run=[ordered]@{runId=$run.id;runNumber=$run.run_number;runAttempt=$run.run_attempt;event=$run.event;headSha=$run.head_sha;headBranch=$run.head_branch;createdAt=$run.created_at;updatedAt=$run.updated_at;conclusion=$run.conclusion};artifactsDiscovered=@($artifacts).Count;artifactsValidated=$validated;localCommitSha=$localSha;localTreeSha=$localTree;remoteHeadSha=$headSha;remoteHeadTreeSha=$headTree;remoteMergeSha=$mergeSha;remoteMergeTreeSha=$mergeTree;CommitIdentityMatch=$commitMatch;TreeIdentityMatch=$treeMatch;ContentEquivalent=$treeMatch}
}catch{$parts=$_.Exception.Message-split'\|',3;$exitCode=if($parts.Count-ge3){[int]$parts[0]}else{$codes.Transport};$errorCode=if($parts.Count-ge3){$parts[1]}else{'AUDIT_BROKEN'};$result=[ordered]@{status='FAIL';errorCode=$errorCode;transportStatus=$transportStatus;message=if($parts.Count-ge3){$parts[2]}else{$_.Exception.Message};remoteHeadSha=$headSha;remoteHeadTreeSha=$headTree;remoteMergeSha=$mergeSha;remoteMergeTreeSha=$mergeTree;artifactsDiscovered=if($null-ne$artifacts){@($artifacts).Count}else{$null};runId=if($null-ne$run){$run.id}else{$null}}}
$result|ConvertTo-Json -Depth 12|Set-Content (Join-Path $out 'audit-result.json') -Encoding utf8NoBOM;Write-Host "Audit status: $($result.status), transport: $transportStatus, code: $errorCode";exit $exitCode
