Set-StrictMode -Version Latest
function Assert-Properties($Object,[string[]]$Allowed,[string]$Context){if($null-eq$Object){throw "$Context is required"};foreach($name in $Object.PSObject.Properties.Name){if($Allowed-notcontains$name){throw "Unexpected $Context property: $name"}}}
function Assert-String($Object,[string]$Name,[switch]$Sha){$v=$Object.$Name;if($v-isnot[string]-or[string]::IsNullOrWhiteSpace($v)){throw "$Name must be a non-empty string"};if($Sha-and$v-notmatch'^[0-9a-f]{40}$'){throw "$Name must be a lowercase 40-character SHA"}}
function Assert-Integer($Object,[string]$Name,[int]$Minimum=0){$v=$Object.$Name;if($v-isnot[int]-and$v-isnot[long]){throw "$Name must be an integer"};if($v-lt$Minimum){throw "$Name must be at least $Minimum"}}
function Assert-Boolean($Object,[string]$Name){if($Object.$Name-isnot[bool]){throw "$Name must be a boolean"}}
function Assert-StringArray($Value,[string]$Name,[switch]$NonEmpty,[switch]$Unique){if($Value-isnot[object[]]){throw "$Name must be an array"};foreach($v in $Value){if($v-isnot[string]-or[string]::IsNullOrWhiteSpace($v)){throw "$Name entries must be non-empty strings"}};if($NonEmpty-and$Value.Count-eq 0){throw "$Name must not be empty"};if($Unique-and@($Value|Select-Object -Unique).Count-ne$Value.Count){throw "$Name must contain unique values"}}
function Test-BusinessOSScenario($Scenario){
 $allowed='name','status','fixturePrepared','recoveryOrigin','recoveryOpened','catalogLoaded','catalogItemCount','validBackupCount','invalidBackupCount','restoreDisabledWithoutSelection','confirmationCancelPassed','backNavigationPassed','restoreStarted','restoreSucceeded','postRestoreStartupSucceeded','fixtureValidation','stableSamplesRequired','stableSamplesObserved','stableWindowStatePassed','finalWindowCount','finalMainWindowCount','finalFailureWindowCount','finalRecoveryWindowCount','closeDispatchMethod','shutdownMethod','exited','exitCode','diagnosticFile';Assert-Properties $Scenario $allowed scenario
 foreach($n in 'name','status','recoveryOrigin','fixtureValidation','closeDispatchMethod','shutdownMethod','diagnosticFile'){Assert-String $Scenario $n};foreach($n in 'fixturePrepared','recoveryOpened','catalogLoaded','restoreDisabledWithoutSelection','confirmationCancelPassed','backNavigationPassed','restoreStarted','restoreSucceeded','postRestoreStartupSucceeded','stableWindowStatePassed','exited'){Assert-Boolean $Scenario $n};foreach($n in 'catalogItemCount','validBackupCount','invalidBackupCount','stableSamplesRequired','stableSamplesObserved','finalWindowCount','finalMainWindowCount','finalFailureWindowCount','finalRecoveryWindowCount','exitCode'){Assert-Integer $Scenario $n}
 if($Scenario.status-ne'PASS'-or-not$Scenario.exited-or$Scenario.exitCode-ne 0-or$Scenario.shutdownMethod-eq'Kill'){throw "$($Scenario.name) did not finish safely"};if($Scenario.stableSamplesRequired-ne 5-or$Scenario.stableSamplesObserved-ne 5-or-not$Scenario.stableWindowStatePassed){throw "$($Scenario.name) lacks five measured stable samples"}
 $recovery=$Scenario.name-like'RecoveryFrom*';if($Scenario.fixturePrepared-ne$recovery){throw "$($Scenario.name) fixturePrepared is inconsistent"};$origin=switch($Scenario.name){RecoveryFromReady{'MainWindow'}RecoveryFromStartupFailure{'StartupFailure'}default{'None'}};if($Scenario.recoveryOrigin-ne$origin){throw "$($Scenario.name) recoveryOrigin is inconsistent"}
 $expected=if($Scenario.name-eq'PersistenceFailure'){@(1,0,1,0)}else{@(1,1,0,0)};if($Scenario.finalWindowCount-ne$expected[0]-or$Scenario.finalMainWindowCount-ne$expected[1]-or$Scenario.finalFailureWindowCount-ne$expected[2]-or$Scenario.finalRecoveryWindowCount-ne$expected[3]){throw "$($Scenario.name) final window counts are invalid"}
 if($recovery){foreach($n in 'recoveryOpened','catalogLoaded','restoreDisabledWithoutSelection','confirmationCancelPassed','backNavigationPassed','restoreStarted','restoreSucceeded','postRestoreStartupSucceeded'){if(-not$Scenario.$n){throw "$($Scenario.name).$n must be true"}};if($Scenario.validBackupCount-lt 1-or$Scenario.invalidBackupCount-lt 1-or$Scenario.fixtureValidation-ne'PASS'){throw "$($Scenario.name) recovery evidence is incomplete"}}
}
function Test-BusinessOSCiEvidence{
 [CmdletBinding()]param([Parameter(Mandatory)][object]$Evidence)
 $required='schemaVersion','generatedAtUtc','repository','eventName','workflowName','runId','runAttempt','jobKey','checkoutKind','commitSha','commitTreeSha','pullRequestNumber','pullRequestHeadSha','pullRequestMergeSha','runnerOs','runnerArch','runnerImage','dotnetVersion','powershellVersion','gateName','gateStatus','startedAtUtc','completedAtUtc','durationSeconds','lastCompletedStage','formatStatus','buildStatus','warnings','errors','tests','vulnerabilities','migrations','smoke','failure';Assert-Properties $Evidence $required summary;foreach($n in $required){if($Evidence.PSObject.Properties.Name-notcontains$n){throw "Missing property: $n"}}
 if(($Evidence.schemaVersion-isnot[int]-and$Evidence.schemaVersion-isnot[long])-or$Evidence.schemaVersion-ne 1){throw 'schemaVersion must equal 1'};foreach($n in 'repository','eventName','workflowName','jobKey','runnerOs','runnerArch','runnerImage','dotnetVersion','powershellVersion','lastCompletedStage'){Assert-String $Evidence $n};foreach($n in 'commitSha','commitTreeSha'){Assert-String $Evidence $n -Sha};foreach($n in 'generatedAtUtc','startedAtUtc','completedAtUtc'){try{[DateTimeOffset]::Parse([string]$Evidence.$n)|Out-Null}catch{throw "$n must be date-time"}}
 if($Evidence.gateName-notin'cross-platform','windows'-or$Evidence.gateStatus-notin'PASS','FAIL','NOT_RUN'-or$Evidence.checkoutKind-notin'pull-request-merge','branch-head','local'){throw 'Invalid gate or checkout status'};foreach($n in 'formatStatus','buildStatus'){if($Evidence.$n-notin'PASS','FAIL','NOT_RUN'){throw "Invalid $n"}};Assert-StringArray @($Evidence.warnings) warnings;Assert-StringArray @($Evidence.errors) errors;Assert-StringArray @($Evidence.failure.diagnosticFiles) diagnosticFiles
 Assert-Properties $Evidence.tests @('discovered','executed','passed','failed','skipped','trxFiles') tests;foreach($n in 'discovered','executed','passed','failed','skipped'){Assert-Integer $Evidence.tests $n};Assert-StringArray @($Evidence.tests.trxFiles) trxFiles -Unique
 Assert-Properties $Evidence.vulnerabilities @('status','knownVulnerabilityCount','checkedTargets') vulnerabilities;Assert-Integer $Evidence.vulnerabilities knownVulnerabilityCount;Assert-StringArray @($Evidence.vulnerabilities.checkedTargets) checkedTargets -Unique
 Assert-Properties $Evidence.migrations @('status','pendingModelChanges','newMigrationCreated','snapshotModified') migrations;foreach($n in 'pendingModelChanges','newMigrationCreated','snapshotModified'){Assert-Boolean $Evidence.migrations $n}
 Assert-Properties $Evidence.failure @('stage','message','diagnosticFiles') failure;Assert-String $Evidence.failure stage;Assert-String $Evidence.failure message
 if($Evidence.gateStatus-eq'PASS'){if($Evidence.failure.stage-ne'none'-or$Evidence.failure.message-ne'none'-or@($Evidence.errors).Count-ne 0-or$Evidence.lastCompletedStage-ne'complete'-or$Evidence.formatStatus-ne'PASS'-or$Evidence.buildStatus-ne'PASS'){throw 'PASS completion evidence is inconsistent'};if($Evidence.checkoutKind-ne'local'){Assert-Integer $Evidence runId 1;Assert-Integer $Evidence runAttempt 1};Assert-StringArray @($Evidence.tests.trxFiles) trxFiles -NonEmpty -Unique;Assert-StringArray @($Evidence.vulnerabilities.checkedTargets) checkedTargets -NonEmpty -Unique;if($Evidence.tests.executed-le 0-or$Evidence.tests.discovered-ne$Evidence.tests.executed-or$Evidence.tests.passed-ne$Evidence.tests.executed-or$Evidence.tests.failed-ne 0-or$Evidence.tests.skipped-ne 0){throw 'PASS tests are inconsistent'};if($Evidence.vulnerabilities.status-ne'PASS'-or$Evidence.vulnerabilities.knownVulnerabilityCount-ne 0-or$Evidence.migrations.status-ne'PASS'-or$Evidence.migrations.pendingModelChanges-or$Evidence.migrations.newMigrationCreated-or$Evidence.migrations.snapshotModified){throw 'PASS engineering checks are inconsistent'}}elseif($Evidence.gateStatus-eq'FAIL'){if($Evidence.failure.stage-eq'none'-or$Evidence.failure.message-eq'none'){throw 'FAIL requires failure details'}}
 Assert-Properties $Evidence.smoke @('requiredScenarioCount','executedScenarioCount','passedScenarioCount','failedScenarioCount','scenarios') smoke;foreach($n in 'requiredScenarioCount','executedScenarioCount','passedScenarioCount','failedScenarioCount'){Assert-Integer $Evidence.smoke $n};if($Evidence.smoke.passedScenarioCount+$Evidence.smoke.failedScenarioCount-ne$Evidence.smoke.executedScenarioCount){throw 'Smoke counts are inconsistent'}
 if($Evidence.gateStatus-eq'PASS'-and$Evidence.gateName-eq'cross-platform'){if($Evidence.smoke.requiredScenarioCount-ne 0-or$Evidence.smoke.executedScenarioCount-ne 0-or@($Evidence.smoke.scenarios).Count-ne 0){throw 'Cross-platform smoke must be empty'}}elseif($Evidence.gateStatus-eq'PASS'-and$Evidence.gateName-eq'windows'){$names='Ready','PersistenceFailure','PersistenceFailureThenReady','RecoveryFromReady','RecoveryFromStartupFailure';if($Evidence.smoke.requiredScenarioCount-ne 5-or$Evidence.smoke.executedScenarioCount-ne 5-or$Evidence.smoke.passedScenarioCount-ne 5-or$Evidence.smoke.failedScenarioCount-ne 0-or@($Evidence.smoke.scenarios).Count-ne 5){throw 'Windows PASS requires five scenarios'};$actual=@($Evidence.smoke.scenarios|ForEach-Object name);if(@($actual|Select-Object -Unique).Count-ne 5-or@($names|Where-Object{$actual-notcontains$_}).Count){throw 'Windows scenario identities are invalid'};foreach($s in $Evidence.smoke.scenarios){Test-BusinessOSScenario $s}}
 $true
}
function Test-BusinessOSManifest{[CmdletBinding()]param([Parameter(Mandatory)][string]$Root,[Parameter(Mandatory)][object]$Manifest);$seen=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal);foreach($entry in @($Manifest.files)){$p=[string]$entry.relativePath;if([string]::IsNullOrWhiteSpace($p)-or[IO.Path]::IsPathRooted($p)-or$p-split'[/\\]' -contains'..'-or-not$seen.Add($p)){throw "Unsafe or duplicate manifest path: $p"};$full=[IO.Path]::GetFullPath((Join-Path $Root $p));if(-not$full.StartsWith(([IO.Path]::GetFullPath($Root)+[IO.Path]::DirectorySeparatorChar))-or-not(Test-Path -LiteralPath $full -PathType Leaf)){throw "Manifest file missing or escaped: $p"};$f=Get-Item -LiteralPath $full;if($f.Length-ne[long]$entry.sizeBytes-or(Get-FileHash -LiteralPath $full -Algorithm SHA256).Hash.ToLowerInvariant()-ne$entry.sha256){throw "Manifest integrity mismatch: $p"}};$actual=@(Get-ChildItem $Root -Recurse -File|Where-Object Name -ne 'manifest.json'|ForEach-Object{[IO.Path]::GetRelativePath($Root,$_.FullName).Replace('\','/')});foreach($p in $actual){if(-not$seen.Contains($p)){throw "Unmanifested file: $p"}};if($actual.Count-ne$seen.Count){throw 'Manifest coverage mismatch'};$true}
Export-ModuleMember -Function Test-BusinessOSCiEvidence,Test-BusinessOSManifest
