Set-StrictMode -Version Latest
function Assert-Properties($Object,[string[]]$Allowed,[string]$Context){if($null-eq$Object){throw "$Context is required"};foreach($name in $Object.PSObject.Properties.Name){if($Allowed-notcontains$name){throw "Unexpected $Context property: $name"}}}
function Assert-String($Object,[string]$Name,[switch]$Sha){$v=$Object.$Name;if($v-isnot[string]-or[string]::IsNullOrWhiteSpace($v)){throw "$Name must be a non-empty string"};if($Sha-and$v-notmatch'^[0-9a-f]{40}$'){throw "$Name must be a lowercase 40-character SHA"}}
function Assert-Integer($Object,[string]$Name,[int]$Minimum=0){$v=$Object.$Name;if($v-isnot[int]-and$v-isnot[long]){throw "$Name must be an integer"};if($v-lt$Minimum){throw "$Name must be at least $Minimum"}}
function ConvertTo-BusinessOSRunNumber([AllowNull()][string]$Value,[string]$Name,[bool]$IsLocal){
 if($IsLocal-and[string]::IsNullOrWhiteSpace($Value)){return [long]0}
 $number=[long]0
 if(-not[long]::TryParse($Value,[Globalization.NumberStyles]::None,[Globalization.CultureInfo]::InvariantCulture,[ref]$number)){throw "$Name must be an invariant-culture Int64 value"}
 $number
}
function New-BusinessOSCiEvidenceSummary{
 [CmdletBinding()]param([Parameter(Mandatory)][hashtable]$Values)
 $defaults=[ordered]@{
  schemaVersion=1;generatedAtUtc=[DateTimeOffset]::UtcNow.ToString('o');repository='local';eventName='local';workflowName='local';runId=[long]0;runAttempt=[long]0;jobKey='cross-platform';checkoutKind='local';commitSha=('0'*40);commitTreeSha=('0'*40);pullRequestNumber=$null;pullRequestHeadSha=$null;pullRequestMergeSha=$null;runnerOs=[Runtime.InteropServices.RuntimeInformation]::OSDescription;runnerArch=[Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString();runnerImage='local';dotnetVersion='unknown';powershellVersion=$PSVersionTable.PSVersion.ToString();gateName='cross-platform';gateStatus='FAIL';startedAtUtc=[DateTimeOffset]::UtcNow.ToString('o');completedAtUtc=[DateTimeOffset]::UtcNow.ToString('o');durationSeconds=0.0;lastCompletedStage='none';formatStatus='NOT_RUN';buildStatus='NOT_RUN';warnings=[string[]]@();errors=[string[]]@();tests=[ordered]@{discovered=0;executed=0;passed=0;failed=0;skipped=0;trxFiles=[string[]]@()};vulnerabilities=[ordered]@{status='NOT_RUN';knownVulnerabilityCount=0;checkedTargets=[string[]]@()};migrations=[ordered]@{status='NOT_RUN';pendingModelChanges=$false;newMigrationCreated=$false;snapshotModified=$false};smoke=[ordered]@{requiredScenarioCount=0;executedScenarioCount=0;passedScenarioCount=0;failedScenarioCount=0;scenarios=@()};failure=[ordered]@{stage='initialization';message='CI evidence generation failed';diagnosticFiles=[string[]]@()}
 }
 foreach($key in $Values.Keys){if(-not$defaults.Contains($key)){throw "Unexpected summary model property: $key"};$defaults[$key]=$Values[$key]}
 $isLocal=$defaults.checkoutKind-eq'local'
 $defaults.runId=ConvertTo-BusinessOSRunNumber ([string]$defaults.runId) runId $isLocal
 $defaults.runAttempt=ConvertTo-BusinessOSRunNumber ([string]$defaults.runAttempt) runAttempt $isLocal
 if($isLocal){if($defaults.runId-ne 0-or$defaults.runAttempt-ne 0){throw 'Local runId and runAttempt must equal zero'}}elseif($defaults.runId-lt 1-or$defaults.runAttempt-lt 1){throw 'GitHub Actions runId and runAttempt must be positive'}
 [pscustomobject]$defaults
}
function Write-BusinessOSCiEvidenceFallback{
 [CmdletBinding()]param([Parameter(Mandatory)][ValidateSet('cross-platform','windows')][string]$Gate,[Parameter(Mandatory)][string]$Root,[Parameter(Mandatory)][string]$FailureStage,[Parameter(Mandatory)][string]$FailureMessage,[Parameter(Mandatory)][string]$GeneratorError,[Parameter(Mandatory)][string]$StartedAtUtc,[string]$LastCompletedStage='none',[string]$FormatStatus='NOT_RUN',[string]$BuildStatus='NOT_RUN')
 $now=[DateTimeOffset]::UtcNow;$start=[DateTimeOffset]::Parse($StartedAtUtc,[Globalization.CultureInfo]::InvariantCulture)
 $sha=(& git -C $Root rev-parse HEAD).Trim();$tree=(& git -C $Root show -s --format=%T $sha).Trim();$actions=[bool]$env:GITHUB_ACTIONS
 $dotnetVersion=(Get-Content (Join-Path $Root 'eng/environment.lock.json') -Raw|ConvertFrom-Json).dotnetSdk
 $hasGateFailure=$FailureStage-ne'none'-and$FailureMessage-ne'none'
 $effectiveStage=if($hasGateFailure){$FailureStage}else{'summary-generation'};$effectiveMessage=if($hasGateFailure){$FailureMessage}else{"Summary generation failed: $GeneratorError"}
 $values=@{gateName=$Gate;gateStatus='FAIL';generatedAtUtc=$now.ToString('o');startedAtUtc=$start.ToString('o');completedAtUtc=$now.ToString('o');durationSeconds=[math]::Max(0,[math]::Round(($now-$start).TotalSeconds,3));lastCompletedStage=$LastCompletedStage;formatStatus=$FormatStatus;buildStatus=$BuildStatus;checkoutKind=if($actions){if($env:GITHUB_EVENT_NAME-eq'pull_request'){'pull-request-merge'}else{'branch-head'}}else{'local'};repository=if($env:GITHUB_REPOSITORY){$env:GITHUB_REPOSITORY}else{'local'};eventName=if($env:GITHUB_EVENT_NAME){$env:GITHUB_EVENT_NAME}else{'local'};workflowName=if($env:GITHUB_WORKFLOW){$env:GITHUB_WORKFLOW}else{'local'};runId=$env:GITHUB_RUN_ID;runAttempt=$env:GITHUB_RUN_ATTEMPT;jobKey=if($env:GITHUB_JOB){$env:GITHUB_JOB}else{$Gate};commitSha=$sha;commitTreeSha=$tree;runnerOs=if($env:RUNNER_OS){$env:RUNNER_OS}else{[Runtime.InteropServices.RuntimeInformation]::OSDescription};runnerArch=if($env:RUNNER_ARCH){$env:RUNNER_ARCH}else{[Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString()};runnerImage=if($env:ImageOS){$env:ImageOS}else{'local'};dotnetVersion=$dotnetVersion;powershellVersion=$PSVersionTable.PSVersion.ToString();warnings=[string[]]@("Summary generator error: $GeneratorError");errors=[string[]]@($effectiveMessage);failure=[ordered]@{stage=$effectiveStage;message=$effectiveMessage;diagnosticFiles=[string[]]@()}}
 $summary=New-BusinessOSCiEvidenceSummary $values;$json=$summary|ConvertTo-Json -Depth 30;Test-BusinessOSCiEvidence ($json|ConvertFrom-Json -Depth 30)|Out-Null;$path=Join-Path $Root ".cache/ci-evidence-source/$Gate/summary.json";New-Item -ItemType Directory -Force (Split-Path $path)|Out-Null;$json|Set-Content $path -Encoding utf8NoBOM;$path
}
function Assert-Boolean($Object,[string]$Name){if($Object.$Name-isnot[bool]){throw "$Name must be a boolean"}}
function Assert-StringArray($Value,[string]$Name,[switch]$NonEmpty,[switch]$Unique){if($Value-isnot[object[]]){throw "$Name must be an array"};foreach($v in $Value){if($v-isnot[string]-or[string]::IsNullOrWhiteSpace($v)){throw "$Name entries must be non-empty strings"}};if($NonEmpty-and$Value.Count-eq 0){throw "$Name must not be empty"};if($Unique-and@($Value|Select-Object -Unique).Count-ne$Value.Count){throw "$Name must contain unique values"}}
function Test-BusinessOSScenario($Scenario){
 $allowed='name','status','fixturePrepared','recoveryOrigin','recoveryOpened','catalogLoaded','catalogItemCount','validBackupCount','invalidBackupCount','restoreDisabledWithoutSelection','confirmationCancelPassed','backNavigationPassed','restoreStarted','restoreSucceeded','postRestoreStartupSucceeded','fixtureValidation','stableSamplesRequired','stableSamplesObserved','stableWindowStatePassed','finalWindowCount','finalMainWindowCount','finalFailureWindowCount','finalRecoveryWindowCount','closeDispatchMethod','shutdownMethod','exited','exitCode','diagnosticFile';Assert-Properties $Scenario $allowed scenario
 foreach($n in 'name','status','recoveryOrigin','fixtureValidation','closeDispatchMethod','shutdownMethod','diagnosticFile'){Assert-String $Scenario $n};foreach($n in 'fixturePrepared','recoveryOpened','catalogLoaded','restoreDisabledWithoutSelection','confirmationCancelPassed','backNavigationPassed','restoreStarted','restoreSucceeded','postRestoreStartupSucceeded','stableWindowStatePassed','exited'){Assert-Boolean $Scenario $n};foreach($n in 'catalogItemCount','validBackupCount','invalidBackupCount','stableSamplesRequired','stableSamplesObserved','finalWindowCount','finalMainWindowCount','finalFailureWindowCount','finalRecoveryWindowCount','exitCode'){Assert-Integer $Scenario $n}
 if($Scenario.status-ne'PASS'-or-not$Scenario.exited-or$Scenario.exitCode-ne 0-or$Scenario.shutdownMethod-eq'Kill'){throw "$($Scenario.name) did not finish safely"};if($Scenario.stableSamplesRequired-ne 5-or$Scenario.stableSamplesObserved-ne 5-or-not$Scenario.stableWindowStatePassed){throw "$($Scenario.name) lacks five measured stable samples"}
 $recovery=$Scenario.name-like'RecoveryFrom*';if($Scenario.fixturePrepared-ne$recovery){throw "$($Scenario.name) fixturePrepared is inconsistent"};$origin=switch($Scenario.name){RecoveryFromReady{'MainWindow'}RecoveryFromStartupFailure{'StartupFailure'}default{'None'}};if($Scenario.recoveryOrigin-ne$origin){throw "$($Scenario.name) recoveryOrigin is inconsistent"}
 $expected=if($Scenario.name-eq'PersistenceFailure'){@(1,0,1,0)}else{@(1,1,0,0)};if($Scenario.finalWindowCount-ne$expected[0]-or$Scenario.finalMainWindowCount-ne$expected[1]-or$Scenario.finalFailureWindowCount-ne$expected[2]-or$Scenario.finalRecoveryWindowCount-ne$expected[3]){throw "$($Scenario.name) final window counts are invalid"}
 if($recovery){foreach($n in 'recoveryOpened','catalogLoaded','restoreDisabledWithoutSelection','confirmationCancelPassed','backNavigationPassed','restoreStarted','restoreSucceeded','postRestoreStartupSucceeded'){if(-not$Scenario.$n){throw "$($Scenario.name).$n must be true"}};if($Scenario.validBackupCount-lt 1-or$Scenario.invalidBackupCount-lt 1-or$Scenario.fixtureValidation-ne'PASS'){throw "$($Scenario.name) recovery evidence is incomplete"}}
}
function Test-BusinessOSCiEvidence{
 [CmdletBinding()]param([Parameter(Mandatory)][object]$Evidence)
 $required='schemaVersion','generatedAtUtc','repository','eventName','workflowName','runId','runAttempt','jobKey','checkoutKind','commitSha','commitTreeSha','pullRequestNumber','pullRequestHeadSha','pullRequestMergeSha','runnerOs','runnerArch','runnerImage','dotnetVersion','powershellVersion','gateName','gateStatus','startedAtUtc','completedAtUtc','durationSeconds','lastCompletedStage','formatStatus','buildStatus','warnings','errors','tests','vulnerabilities','migrations','smoke','failure';Assert-Properties $Evidence $required summary;foreach($n in $required){if($Evidence.PSObject.Properties.Name-notcontains$n){throw "Missing property: $n"}}
 if(($Evidence.schemaVersion-isnot[int]-and$Evidence.schemaVersion-isnot[long])-or$Evidence.schemaVersion-ne 1){throw 'schemaVersion must equal 1'};foreach($n in 'runId','runAttempt'){Assert-Integer $Evidence $n};foreach($n in 'repository','eventName','workflowName','jobKey','runnerOs','runnerArch','runnerImage','dotnetVersion','powershellVersion','lastCompletedStage'){Assert-String $Evidence $n};foreach($n in 'commitSha','commitTreeSha'){Assert-String $Evidence $n -Sha};foreach($n in 'generatedAtUtc','startedAtUtc','completedAtUtc'){try{[DateTimeOffset]::Parse([string]$Evidence.$n)|Out-Null}catch{throw "$n must be date-time"}}
 if($Evidence.gateName-notin'cross-platform','windows'-or$Evidence.gateStatus-notin'PASS','FAIL','NOT_RUN'-or$Evidence.checkoutKind-notin'pull-request-merge','branch-head','local'){throw 'Invalid gate or checkout status'};if($Evidence.checkoutKind-eq'local'){if($Evidence.runId-ne 0-or$Evidence.runAttempt-ne 0){throw 'Local runId and runAttempt must equal zero'}}else{Assert-Integer $Evidence runId 1;Assert-Integer $Evidence runAttempt 1};foreach($n in 'formatStatus','buildStatus'){if($Evidence.$n-notin'PASS','FAIL','NOT_RUN'){throw "Invalid $n"}};Assert-StringArray @($Evidence.warnings) warnings;Assert-StringArray @($Evidence.errors) errors;Assert-StringArray @($Evidence.failure.diagnosticFiles) diagnosticFiles
 Assert-Properties $Evidence.tests @('discovered','executed','passed','failed','skipped','trxFiles') tests;foreach($n in 'discovered','executed','passed','failed','skipped'){Assert-Integer $Evidence.tests $n};Assert-StringArray @($Evidence.tests.trxFiles) trxFiles -Unique
 Assert-Properties $Evidence.vulnerabilities @('status','knownVulnerabilityCount','checkedTargets') vulnerabilities;Assert-Integer $Evidence.vulnerabilities knownVulnerabilityCount;Assert-StringArray @($Evidence.vulnerabilities.checkedTargets) checkedTargets -Unique
 Assert-Properties $Evidence.migrations @('status','pendingModelChanges','newMigrationCreated','snapshotModified') migrations;foreach($n in 'pendingModelChanges','newMigrationCreated','snapshotModified'){Assert-Boolean $Evidence.migrations $n}
 Assert-Properties $Evidence.failure @('stage','message','diagnosticFiles') failure;Assert-String $Evidence.failure stage;Assert-String $Evidence.failure message
 if($Evidence.gateStatus-eq'PASS'){if($Evidence.failure.stage-ne'none'-or$Evidence.failure.message-ne'none'-or@($Evidence.errors).Count-ne 0-or$Evidence.lastCompletedStage-ne'complete'-or$Evidence.formatStatus-ne'PASS'-or$Evidence.buildStatus-ne'PASS'){throw 'PASS completion evidence is inconsistent'};Assert-StringArray @($Evidence.tests.trxFiles) trxFiles -NonEmpty -Unique;Assert-StringArray @($Evidence.vulnerabilities.checkedTargets) checkedTargets -NonEmpty -Unique;if($Evidence.tests.executed-le 0-or$Evidence.tests.discovered-ne$Evidence.tests.executed-or$Evidence.tests.passed-ne$Evidence.tests.executed-or$Evidence.tests.failed-ne 0-or$Evidence.tests.skipped-ne 0){throw 'PASS tests are inconsistent'};if($Evidence.vulnerabilities.status-ne'PASS'-or$Evidence.vulnerabilities.knownVulnerabilityCount-ne 0-or$Evidence.migrations.status-ne'PASS'-or$Evidence.migrations.pendingModelChanges-or$Evidence.migrations.newMigrationCreated-or$Evidence.migrations.snapshotModified){throw 'PASS engineering checks are inconsistent'}}elseif($Evidence.gateStatus-eq'FAIL'){if($Evidence.failure.stage-eq'none'-or$Evidence.failure.message-eq'none'){throw 'FAIL requires failure details'}}
 Assert-Properties $Evidence.smoke @('requiredScenarioCount','executedScenarioCount','passedScenarioCount','failedScenarioCount','scenarios') smoke;foreach($n in 'requiredScenarioCount','executedScenarioCount','passedScenarioCount','failedScenarioCount'){Assert-Integer $Evidence.smoke $n};if($Evidence.smoke.passedScenarioCount+$Evidence.smoke.failedScenarioCount-ne$Evidence.smoke.executedScenarioCount){throw 'Smoke counts are inconsistent'}
 if($Evidence.gateStatus-eq'PASS'-and$Evidence.gateName-eq'cross-platform'){if($Evidence.smoke.requiredScenarioCount-ne 0-or$Evidence.smoke.executedScenarioCount-ne 0-or@($Evidence.smoke.scenarios).Count-ne 0){throw 'Cross-platform smoke must be empty'}}elseif($Evidence.gateStatus-eq'PASS'-and$Evidence.gateName-eq'windows'){$names='Ready','PersistenceFailure','PersistenceFailureThenReady','RecoveryFromReady','RecoveryFromStartupFailure';if($Evidence.smoke.requiredScenarioCount-ne 5-or$Evidence.smoke.executedScenarioCount-ne 5-or$Evidence.smoke.passedScenarioCount-ne 5-or$Evidence.smoke.failedScenarioCount-ne 0-or@($Evidence.smoke.scenarios).Count-ne 5){throw 'Windows PASS requires five scenarios'};$actual=@($Evidence.smoke.scenarios|ForEach-Object name);if(@($actual|Select-Object -Unique).Count-ne 5-or@($names|Where-Object{$actual-notcontains$_}).Count){throw 'Windows scenario identities are invalid'};foreach($s in $Evidence.smoke.scenarios){Test-BusinessOSScenario $s}}
 $true
}
function Test-BusinessOSManifest{[CmdletBinding()]param([Parameter(Mandatory)][string]$Root,[Parameter(Mandatory)][object]$Manifest);$seen=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal);foreach($entry in @($Manifest.files)){$p=[string]$entry.relativePath;if([string]::IsNullOrWhiteSpace($p)-or[IO.Path]::IsPathRooted($p)-or$p-split'[/\\]' -contains'..'-or-not$seen.Add($p)){throw "Unsafe or duplicate manifest path: $p"};$full=[IO.Path]::GetFullPath((Join-Path $Root $p));if(-not$full.StartsWith(([IO.Path]::GetFullPath($Root)+[IO.Path]::DirectorySeparatorChar))-or-not(Test-Path -LiteralPath $full -PathType Leaf)){throw "Manifest file missing or escaped: $p"};$f=Get-Item -LiteralPath $full;if($f.Length-ne[long]$entry.sizeBytes-or(Get-FileHash -LiteralPath $full -Algorithm SHA256).Hash.ToLowerInvariant()-ne$entry.sha256){throw "Manifest integrity mismatch: $p"}};$actual=@(Get-ChildItem $Root -Recurse -File|Where-Object Name -ne 'manifest.json'|ForEach-Object{[IO.Path]::GetRelativePath($Root,$_.FullName).Replace('\','/')});foreach($p in $actual){if(-not$seen.Contains($p)){throw "Unmanifested file: $p"}};if($actual.Count-ne$seen.Count){throw 'Manifest coverage mismatch'};$true}
Export-ModuleMember -Function Test-BusinessOSCiEvidence,Test-BusinessOSManifest,New-BusinessOSCiEvidenceSummary,Write-BusinessOSCiEvidenceFallback
