param([Parameter(Mandatory)][ValidateSet('cross-platform','windows')][string]$Gate)
$ErrorActionPreference='Stop';$root=(Resolve-Path "$PSScriptRoot/..").Path;$destination=Join-Path $root "artifacts/ci-evidence/$Gate";if(Test-Path $destination){Remove-Item $destination -Recurse -Force};New-Item -ItemType Directory -Force $destination|Out-Null
$summarySource=Join-Path $root ".cache/ci-evidence-source/$Gate/summary.json"
Import-Module "$PSScriptRoot/BusinessOS.CiEvidence.psm1" -Force
$reason=$null
if(Test-Path $summarySource -PathType Leaf){try{$candidate=Get-Content $summarySource -Raw|ConvertFrom-Json -Depth 30;Test-BusinessOSCiEvidence $candidate|Out-Null}catch{$reason="Existing summary is invalid: $($_.Exception.Message)"}}else{$reason='Gate did not create summary; setup or verifier failed before evidence initialization.'}
if($reason){& "$PSScriptRoot/write-ci-summary.ps1" -Gate $Gate -Status FAIL -FailureStage summary -FailureMessage $reason -LastCompletedStage none -FormatStatus NOT_RUN -BuildStatus NOT_RUN -MinimalFailure}
if(-not(Test-Path $summarySource -PathType Leaf)){throw "Required evidence is missing: $summarySource"}
$summary=Get-Content $summarySource -Raw|ConvertFrom-Json -Depth 30;Test-BusinessOSCiEvidence $summary|Out-Null
Copy-Item $summarySource (Join-Path $destination 'summary.json');$pass=$summary.gateStatus-eq'PASS';$logs=[ordered]@{'setup.log'='.cache/setup.log';'doctor.txt'='.cache/doctor.txt';'tool-versions.log'='.cache/tool-versions.log';"verify-$Gate.log"=".cache/verify-$Gate.log";'environment-tests.log'='.cache/environment-tests.log'};foreach($name in $logs.Keys){$source=Join-Path $root $logs[$name];if(Test-Path $source -PathType Leaf){Copy-Item $source (Join-Path $destination $name)}elseif($pass){throw "Required PASS evidence is missing: $source"}}
$trx=@(Get-ChildItem (Join-Path $root 'artifacts/test-results') -Recurse -File -Filter *.trx -ErrorAction SilentlyContinue);if($pass -and -not $trx){throw 'At least one TRX is required for PASS'};foreach($f in $trx){$rel='trx/'+[IO.Path]::GetRelativePath((Join-Path $root 'artifacts/test-results'),$f.FullName).Replace('\\','/');$target=Join-Path $destination $rel;New-Item -ItemType Directory -Force (Split-Path $target)|Out-Null;Copy-Item -LiteralPath $f.FullName -Destination $target}
if($Gate -eq 'windows'){$diag=Get-ChildItem (Join-Path $root 'artifacts/smoke-test') -Recurse -File -Filter desktop-smoke-diagnostics.txt -ErrorAction SilentlyContinue|Select-Object -First 1;if($pass-and-not$diag){throw 'Windows smoke diagnostics are required'};if($diag){Copy-Item $diag.FullName (Join-Path $destination 'desktop-smoke-diagnostics.txt')};$scenarioFiles=@(Get-ChildItem (Join-Path $root 'artifacts/smoke-test/scenarios') -File -Filter *.json -ErrorAction SilentlyContinue);if($pass-and$scenarioFiles.Count-ne 5){throw 'Exactly five scenario JSON files are required'};if($scenarioFiles.Count-gt 0){New-Item -ItemType Directory -Force (Join-Path $destination scenarios)|Out-Null;Copy-Item -LiteralPath $scenarioFiles.FullName -Destination (Join-Path $destination scenarios)}}
foreach($n in 'ui-tree-sanitized.txt','top-level-windows-sanitized.json','failure-screenshot.png'){$f=Get-ChildItem (Join-Path $root 'artifacts/smoke-test') -Recurse -File -Filter $n -ErrorAction SilentlyContinue|Select-Object -First 1;if($f){Copy-Item $f.FullName (Join-Path $destination $n)}}
$forbidden='(?i)\.(db|db-shm|db-wal|sqlite|sqlite3|tmp|pfx|pem|key)$';$secret='(?i)(Authorization\s*:|Bearer\s+[A-Za-z0-9._-]+|GITHUB_TOKEN|GH_TOKEN|BEGIN PRIVATE KEY|(?:connection\s*string|password|pwd)\s*[=:]\s*[^;\s]+)';$files=@(Get-ChildItem $destination -Recurse -File);foreach($f in $files){if($f.Name -match $forbidden){throw "Forbidden artifact: $($f.Name)"};if($f.Extension -match '^\.(txt|log|json|xml|trx)$'-and(Select-String $f.FullName -Pattern $secret -Quiet)){throw "Secret pattern in artifact: $($f.Name)"}}
$entries=@();foreach($file in ($files|Sort-Object FullName)){$contentType=switch($file.Extension){'.json'{'application/json'}'.png'{'image/png'}'.trx'{'application/xml'}default{'text/plain'}};$entries+=[ordered]@{relativePath=[IO.Path]::GetRelativePath($destination,$file.FullName).Replace('\','/');sizeBytes=$file.Length;sha256=(Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant();contentType=$contentType}};[ordered]@{schemaVersion=1;generatedAtUtc=[DateTimeOffset]::UtcNow.ToString('o');files=$entries}|ConvertTo-Json -Depth 8|Set-Content (Join-Path $destination manifest.json) -Encoding utf8NoBOM
Import-Module "$PSScriptRoot/BusinessOS.CiEvidence.psm1" -Force;$manifest=Read-BusinessOSManifest -Root $destination -Path (Join-Path $destination manifest.json);$summary=Get-Content (Join-Path $destination summary.json) -Raw|ConvertFrom-Json -Depth 30;Test-BusinessOSCiEvidence $summary|Out-Null;Write-Host "Staged and validated $($entries.Count) evidence files in $destination"
