param([string]$EvidencePath)
$ErrorActionPreference='Stop';Import-Module "$PSScriptRoot/BusinessOS.CiEvidence.psm1" -Force
if($EvidencePath){$e=Get-Content (Join-Path $EvidencePath 'summary.json')-Raw|ConvertFrom-Json -Depth 30;Test-BusinessOSCiEvidence $e|Out-Null;if(Test-Path(Join-Path $EvidencePath 'manifest.json')){$m=Get-Content(Join-Path $EvidencePath 'manifest.json')-Raw|ConvertFrom-Json;Test-BusinessOSManifest $EvidencePath $m|Out-Null};Write-Host 'CI evidence validation PASS';exit 0}
$cross=Get-Content "$PSScriptRoot/../tests/fixtures/github-api/green-pr/cross-platform/summary.json"-Raw|ConvertFrom-Json -Depth 30;$windows=Get-Content "$PSScriptRoot/../tests/fixtures/github-api/green-pr/windows/summary.json"-Raw|ConvertFrom-Json -Depth 30
function Clone($x){$x|ConvertTo-Json -Depth 30|ConvertFrom-Json -Depth 30};$failed=0
function Reject([string]$Name,$Base,[scriptblock]$Mutation){$x=Clone $Base;& $Mutation $x;try{Test-BusinessOSCiEvidence $x|Out-Null;Write-Error "$Name accepted";$script:failed++}catch{Write-Host "$Name rejected"}}
Reject schema-version $cross {param($x)$x.schemaVersion=2};Reject boolean-string $windows {param($x)$x.smoke.scenarios[0].exited='true'};Reject integer-string $cross {param($x)$x.tests.executed='10'};Reject empty-repository $cross {param($x)$x.repository=''};Reject empty-workflow $cross {param($x)$x.workflowName=''};Reject empty-job-key $cross {param($x)$x.jobKey=''};Reject pass-failure-stage $cross {param($x)$x.failure.stage='tests'};Reject pass-errors $cross {param($x)$x.errors=@('bad')};Reject empty-trx $cross {param($x)$x.tests.trxFiles=@()};Reject duplicate-trx $cross {param($x)$x.tests.trxFiles+=@($x.tests.trxFiles[0])};Reject empty-targets $cross {param($x)$x.vulnerabilities.checkedTargets=@()};Reject sample-count $windows {param($x)$x.smoke.scenarios[0].stableSamplesObserved=4};Reject fixture-consistency $windows {param($x)$x.smoke.scenarios[0].fixturePrepared=$true};Reject recovery-origin $windows {param($x)$x.smoke.scenarios[3].recoveryOrigin='StartupFailure'};Reject shutdown-kill $windows {param($x)$x.smoke.scenarios[0].shutdownMethod='Kill'};Reject empty-diagnostic $windows {param($x)$x.smoke.scenarios[0].diagnosticFile=''}
foreach($scenario in @($windows.smoke.scenarios)){Reject "window-state-$($scenario.name)" $windows {param($x)$s=@($x.smoke.scenarios|Where-Object name -eq $scenario.name)[0];$s.finalWindowCount=2}.GetNewClosure()}
$fail=Clone $cross;$fail.gateStatus='FAIL';$fail.failure.stage='tests';$fail.failure.message='controlled';$fail.lastCompletedStage='build';Reject fail-stage-none $fail {param($x)$x.failure.stage='none'};Reject fail-message-none $fail {param($x)$x.failure.message='none'}
Write-Host "failed $failed";exit $(if($failed){1}else{0})
