param([string]$EvidencePath)
$ErrorActionPreference='Stop';Import-Module "$PSScriptRoot/BusinessOS.CiEvidence.psm1" -Force
if($EvidencePath){$e=Get-Content (Join-Path $EvidencePath 'summary.json')-Raw|ConvertFrom-Json -Depth 30;Test-BusinessOSCiEvidence $e|Out-Null;if(Test-Path(Join-Path $EvidencePath 'manifest.json')){$m=Read-BusinessOSManifest -Root $EvidencePath -Path (Join-Path $EvidencePath 'manifest.json')};Write-Host 'CI evidence validation PASS';exit 0}
$cross=Get-Content "$PSScriptRoot/../tests/fixtures/github-api/green-pr/cross-platform/summary.json"-Raw|ConvertFrom-Json -Depth 30;$windows=Get-Content "$PSScriptRoot/../tests/fixtures/github-api/green-pr/windows/summary.json"-Raw|ConvertFrom-Json -Depth 30
function Clone($x){$x|ConvertTo-Json -Depth 30|ConvertFrom-Json -Depth 30};$failed=0
function Reject([string]$Name,$Base,[scriptblock]$Mutation){$x=Clone $Base;& $Mutation $x;try{Test-BusinessOSCiEvidence $x|Out-Null;Write-Error "$Name accepted";$script:failed++}catch{Write-Host "$Name rejected"}}
$schemaPath="$PSScriptRoot/schemas/ci-evidence.schema.json"
function Schema-Accepts($Value){$json=$Value|ConvertTo-Json -Depth 30;return [bool]($json|Test-Json -SchemaFile $schemaPath -ErrorAction SilentlyContinue)}
function Reject-Both([string]$Name,$Base,[scriptblock]$Mutation){$x=Clone $Base;&$Mutation $x;$runtimeAccepted=$true;try{Test-BusinessOSCiEvidence $x|Out-Null}catch{$runtimeAccepted=$false};$schemaAccepted=Schema-Accepts $x;if($runtimeAccepted-or$schemaAccepted){Write-Error "$Name parity failure: runtime=$runtimeAccepted schema=$schemaAccepted";$script:failed++}else{Write-Host "$Name rejected by runtime and schema"}}
foreach($canonical in $cross,$windows){Test-BusinessOSCiEvidence $canonical|Out-Null;if(-not(Schema-Accepts $canonical)){Write-Error 'Canonical fixture failed JSON Schema';$failed++}};Write-Host 'Canonical fixtures accepted by runtime and schema'
Reject schema-version $cross {param($x)$x.schemaVersion=2};Reject boolean-string $windows {param($x)$x.smoke.scenarios[0].exited='true'};Reject integer-string $cross {param($x)$x.tests.executed='10'};Reject empty-repository $cross {param($x)$x.repository=''};Reject empty-workflow $cross {param($x)$x.workflowName=''};Reject empty-job-key $cross {param($x)$x.jobKey=''};Reject pass-failure-stage $cross {param($x)$x.failure.stage='tests'};Reject pass-errors $cross {param($x)$x.errors=@('bad')};Reject empty-trx $cross {param($x)$x.tests.trxFiles=@()};Reject duplicate-trx $cross {param($x)$x.tests.trxFiles+=@($x.tests.trxFiles[0])};Reject empty-targets $cross {param($x)$x.vulnerabilities.checkedTargets=@()};Reject sample-count $windows {param($x)$x.smoke.scenarios[0].stableSamplesObserved=4};Reject fixture-consistency $windows {param($x)$x.smoke.scenarios[0].fixturePrepared=$true};Reject recovery-origin $windows {param($x)$x.smoke.scenarios[3].recoveryOrigin='StartupFailure'};Reject shutdown-kill $windows {param($x)$x.smoke.scenarios[0].shutdownMethod='Kill'};foreach($bad in 'NOT RUN','NOT_RUN','UNKNOWN','NOT CAPTURED','None',''){Reject "bad-close-$bad" $windows {param($x)$x.smoke.scenarios[0].closeDispatchMethod=$bad}.GetNewClosure();Reject "bad-shutdown-$bad" $windows {param($x)$x.smoke.scenarios[0].shutdownMethod=$bad}.GetNewClosure()};Reject unregistered-close $windows {param($x)$x.smoke.scenarios[0].closeDispatchMethod='Other'};Reject unregistered-shutdown $windows {param($x)$x.smoke.scenarios[0].shutdownMethod='Other'};Reject empty-diagnostic $windows {param($x)$x.smoke.scenarios[0].diagnosticFile=''}
Reject warnings-scalar $cross {param($x)$x.warnings='warning'};Reject errors-scalar $cross {param($x)$x.errors='error'};Reject trx-scalar $cross {param($x)$x.tests.trxFiles='result.trx'};Reject targets-scalar $cross {param($x)$x.vulnerabilities.checkedTargets='solution'};Reject diagnostics-scalar $cross {param($x)$x.failure.diagnosticFiles='log.txt'};Reject scenarios-scalar $windows {param($x)$x.smoke.scenarios=$x.smoke.scenarios[0]};Reject negative-duration $cross {param($x)$x.durationSeconds=-1};Reject bad-vulnerability-status $cross {param($x)$x.vulnerabilities.status='UNKNOWN'};Reject bad-migration-status $cross {param($x)$x.migrations.status='UNKNOWN'};Reject pr-number-string $cross {param($x)$x.pullRequestNumber='20'};Reject branch-pr-identity $cross {param($x)$x.checkoutKind='branch-head'}
foreach($scenario in @($windows.smoke.scenarios)){Reject "window-state-$($scenario.name)" $windows {param($x)$s=@($x.smoke.scenarios|Where-Object name -eq $scenario.name)[0];$s.finalWindowCount=2}.GetNewClosure()}
$fail=Clone $cross;$fail.gateStatus='FAIL';$fail.failure.stage='tests';$fail.failure.message='controlled';$fail.lastCompletedStage='build';$notRun=Clone $fail;$notRun.migrations.status='NOT_RUN';$notRun.migrations.pendingModelChanges=$null;$notRun.migrations.newMigrationCreated=$null;$notRun.migrations.snapshotModified=$null;Test-BusinessOSCiEvidence $notRun|Out-Null;Reject not-run-false $notRun {param($x)$x.migrations.pendingModelChanges=$false};Reject pass-null $cross {param($x)$x.migrations.pendingModelChanges=$null};Reject pass-true $cross {param($x)$x.migrations.snapshotModified=$true}
Reject-Both parity-array $cross {param($x)$x.warnings='warning'};Reject-Both parity-status $cross {param($x)$x.vulnerabilities.status='UNKNOWN'};Reject-Both parity-duration $cross {param($x)$x.durationSeconds=-1};Reject-Both parity-pr $cross {param($x)$x.pullRequestNumber=$null};Reject-Both parity-branch $cross {param($x)$x.checkoutKind='branch-head'};Reject-Both parity-not-run $notRun {param($x)$x.migrations.pendingModelChanges=$false};Reject-Both parity-pass-null $cross {param($x)$x.migrations.pendingModelChanges=$null};Reject-Both parity-pass-true $cross {param($x)$x.migrations.pendingModelChanges=$true};Reject-Both parity-run-id $cross {param($x)$x.runId=0};Reject-Both parity-run-attempt $cross {param($x)$x.runAttempt=0}
Reject-Both windows-status $windows {param($x)$x.smoke.scenarios[0].status='FAIL'}
Reject-Both windows-exited $windows {param($x)$x.smoke.scenarios[0].exited=$false}
Reject-Both windows-exit-code $windows {param($x)$x.smoke.scenarios[0].exitCode=1}
Reject-Both windows-samples-required $windows {param($x)$x.smoke.scenarios[0].stableSamplesRequired=4}
Reject-Both windows-samples-observed $windows {param($x)$x.smoke.scenarios[0].stableSamplesObserved=4}
Reject-Both windows-stability $windows {param($x)$x.smoke.scenarios[0].stableWindowStatePassed=$false}
foreach($bad in 'Kill','NOT RUN','NOT_RUN','UNKNOWN','NOT CAPTURED','None','','Other'){Reject-Both "windows-close-$bad" $windows {param($x)$x.smoke.scenarios[0].closeDispatchMethod=$bad}.GetNewClosure();Reject-Both "windows-shutdown-$bad" $windows {param($x)$x.smoke.scenarios[0].shutdownMethod=$bad}.GetNewClosure()}
Reject-Both windows-mixed-pair $windows {param($x)$s=@($x.smoke.scenarios|Where-Object name -eq 'PersistenceFailure')[0];$s.closeDispatchMethod='CloseButton';$s.shutdownMethod='CloseMainWindow'}
foreach($scenario in @($windows.smoke.scenarios)){Reject-Both "windows-counts-$($scenario.name)" $windows {param($x)$s=@($x.smoke.scenarios|Where-Object name -eq $scenario.name)[0];$s.finalWindowCount=2}.GetNewClosure()}
Reject-Both windows-missing-scenario $windows {param($x)$x.smoke.scenarios=@($x.smoke.scenarios|Select-Object -First 4);$x.smoke.executedScenarioCount=4;$x.smoke.passedScenarioCount=4}
Reject-Both windows-duplicate-name $windows {param($x)$x.smoke.scenarios[1].name='Ready'}
Reject-Both windows-unknown-name $windows {param($x)$x.smoke.scenarios[1].name='Other'}
Reject-Both windows-fixture $windows {param($x)$x.smoke.scenarios[0].fixturePrepared=$true}
Reject-Both windows-origin $windows {param($x)$x.smoke.scenarios[3].recoveryOrigin='StartupFailure'}
foreach($flag in 'recoveryOpened','catalogLoaded','restoreDisabledWithoutSelection','confirmationCancelPassed','backNavigationPassed','restoreStarted','restoreSucceeded','postRestoreStartupSucceeded'){Reject-Both "windows-recovery-$flag" $windows {param($x)$x.smoke.scenarios[3].$flag=$false}.GetNewClosure()}
Reject-Both windows-valid-backups $windows {param($x)$x.smoke.scenarios[3].validBackupCount=0}
Reject-Both windows-invalid-backups $windows {param($x)$x.smoke.scenarios[3].invalidBackupCount=0}
Reject-Both windows-fixture-validation $windows {param($x)$x.smoke.scenarios[3].fixtureValidation='FAIL'}
Reject fail-stage-none $fail {param($x)$x.failure.stage='none'};Reject fail-message-none $fail {param($x)$x.failure.message='none'}
& pwsh -NoProfile -File "$PSScriptRoot/test-write-ci-summary.ps1";if($LASTEXITCODE){$failed++}
Write-Host "failed $failed";exit $(if($failed){1}else{0})
