[CmdletBinding()]param([switch]$SummaryGenerationRegressionTest)
$ErrorActionPreference='Stop';. "$PSScriptRoot/activate-environment.ps1";Import-Module "$PSScriptRoot/BusinessOS.Engineering.psm1" -Force
$Root=Get-BusinessOSRepoRoot;$started=[DateTimeOffset]::UtcNow.ToString('o');$stage='initialization';$last='none';$exitCode=0;$failure='none';$formatStatus='NOT_RUN';$buildStatus='NOT_RUN';$art=Join-Path $Root 'artifacts/test-results';if(Test-Path $art){Remove-Item $art -Recurse -Force};New-Item -ItemType Directory -Force $art|Out-Null
function Run([string]$Name,[scriptblock]$Action){$script:stage=$Name;&$Action;$script:last=$Name}
try{
 if($SummaryGenerationRegressionTest){$stage='complete';$last='complete';$formatStatus='PASS';$buildStatus='PASS'}else{
 Run doctor {Invoke-CheckedCommand pwsh @('-NoProfile','-File',"$PSScriptRoot/doctor.ps1",'-Mode','CrossPlatform','-SkipEnvironmentTests') $Root;Invoke-CheckedCommand pwsh @('-NoProfile','-File',"$PSScriptRoot/check-solution-projects.ps1") $Root}
 Run ci-evidence-contract-tests {Invoke-CheckedCommand pwsh @('-NoProfile','-File',"$PSScriptRoot/test-ci-evidence.ps1") $Root}
 Run ci-evidence-cleanup {foreach($path in "$Root/.cache/ci-evidence-source/cross-platform","$Root/artifacts/ci-evidence/cross-platform"){if(Test-Path -LiteralPath $path){Remove-Item -LiteralPath $path -Recurse -Force}}}
 Run environment-tests {Invoke-CheckedCommand pwsh @('-NoProfile','-File',"$Root/tests/environment/Environment.Tests.ps1") $Root}
 Run restore {Invoke-CheckedCommand dotnet @('tool','restore') $Root;Invoke-CheckedCommand dotnet @('restore','BusinessOS.CrossPlatform.slnf') $Root}
 Run format {Invoke-CheckedCommand dotnet @('format','BusinessOS.CrossPlatform.slnf','--verify-no-changes') $Root;$script:formatStatus='PASS'}
 Run build {Invoke-CheckedCommand dotnet @('build','BusinessOS.CrossPlatform.slnf','-c','Release','--no-restore') $Root;$script:buildStatus='PASS'}
 Run tests {Invoke-CheckedCommand dotnet @('test','BusinessOS.CrossPlatform.slnf','-c','Release','--no-build','--logger','trx','--results-directory',$art) $Root}
 Run trx-verification {Invoke-CheckedCommand pwsh @('-NoProfile','-File',"$PSScriptRoot/verify-test-results.ps1",'-ResultsDirectory',$art) $Root;Invoke-CheckedCommand pwsh @('-NoProfile','-File',"$PSScriptRoot/test-verify-test-results.ps1") $Root}
 Run vulnerability-scan {Invoke-CheckedCommand pwsh @('-NoProfile','-File',"$PSScriptRoot/check-vulnerable-packages.ps1",'-ProjectOrSolution','BusinessOS.CrossPlatform.slnf') $Root}
 Run migration-check {$before=@(&git status --porcelain -- 'src/Modules/Companies/BusinessOS.Modules.Companies.Infrastructure/Persistence/Migrations');$output=&dotnet ef migrations has-pending-model-changes --project src/Modules/Companies/BusinessOS.Modules.Companies.Infrastructure/BusinessOS.Modules.Companies.Infrastructure.csproj --startup-project src/Modules/Companies/BusinessOS.Modules.Companies.Infrastructure/BusinessOS.Modules.Companies.Infrastructure.csproj --context CompaniesDbContext 2>&1;if($LASTEXITCODE){throw ($output-join"`n")};$after=@(&git status --porcelain -- 'src/Modules/Companies/BusinessOS.Modules.Companies.Infrastructure/Persistence/Migrations');[ordered]@{status='PASS';pendingModelChanges=($output-join"`n")-notmatch'No changes have been made';newMigrationCreated=$after.Count-gt$before.Count;snapshotModified=[bool]($after-match'ModelSnapshot')}|ConvertTo-Json|Set-Content "$Root/.cache/migration-evidence.json"}
 Run final-doctor {Invoke-CheckedCommand pwsh @('-NoProfile','-File',"$PSScriptRoot/doctor.ps1",'-Mode','CrossPlatform','-SkipEnvironmentTests') $Root};$tracked=@(&git ls-files);if($tracked|Where-Object{$_-match'(^|/)(\.tools|\.cache)/|\.(pfx|pem|key)$'}){throw 'Tracked secret or binary detected'};$stage='complete';$last='complete'}
}catch{$exitCode=if($LASTEXITCODE){$LASTEXITCODE}else{1};$failure=$_.Exception.Message;if($stage-eq'format'){$formatStatus='FAIL'};if($stage-eq'build'){$buildStatus='FAIL'};Write-Host "Gate failure: $($_.Exception.Message)"}
finally{try{& "$PSScriptRoot/write-ci-summary.ps1" -Gate cross-platform -Status $(if($exitCode){'FAIL'}else{'PASS'}) -FailureStage $(if($exitCode){$stage}else{'none'}) -FailureMessage $(if($exitCode){$failure}else{'none'}) -LastCompletedStage $last -StartedAtUtc $started -FormatStatus $formatStatus -BuildStatus $buildStatus}catch{$summaryError=$_;Write-Host "Summary generation failed: $summaryError";& "$PSScriptRoot/write-ci-summary.ps1" -Gate cross-platform -Status FAIL -FailureStage summary -FailureMessage "Summary generation failed: $summaryError" -LastCompletedStage $last -StartedAtUtc $started -FormatStatus $formatStatus -BuildStatus $buildStatus -MinimalFailure;if(-not$exitCode){$exitCode=1}}};if($exitCode){exit $exitCode}
