// <auto-generated />
using System;
using System.Collections.Generic;
using BusinessOS.Modules.Budgeting.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessOS.Modules.Budgeting.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BudgetingDbContext))]
    [Migration("20260816175745_AddSupplierInvoicePosting")]
    partial class AddSupplierInvoicePosting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("BusinessOS.Modules.Budgeting.Domain.ActualCost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("IncurredOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("incurred_on");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_project_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "BusinessOS.Modules.Budgeting.Domain.ActualCost.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "IncurredOn");

                    b.ToTable("actual_costs", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Modules.Budgeting.Domain.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("archived_at_utc IS NULL");

                    b.ToTable("budgets", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Modules.Budgeting.Domain.BudgetLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("budget_version_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "BusinessOS.Modules.Budgeting.Domain.BudgetLine.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("budget_lines", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Modules.Budgeting.Domain.BudgetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("budget_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("BudgetId", "Number")
                        .IsUnique();

                    b.ToTable("budget_versions", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Modules.Budgeting.Domain.ForecastCost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("ExpectedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("expected_on");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_project_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Money", "BusinessOS.Modules.Budgeting.Domain.ForecastCost.Money#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "ExpectedOn");

                    b.ToTable("forecast_costs", (string)null);
                });

            modelBuilder.Entity("BusinessOS.Modules.Budgeting.Domain.SupplierInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_number");

                    b.Property<string>("InvoiceNumberKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_number_key");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<Guid?>("PostedActualCostId")
                        .HasColumnType("TEXT")
                        .HasColumnName("posted_actual_cost_id");

                    b.Property<DateTimeOffset?>("PostedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("posted_at_utc");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("business_project_id");

                    b.Property<string>("SupplierKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("supplier_key");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("supplier_name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "BusinessOS.Modules.Budgeting.Domain.SupplierInvoice.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PostedActualCostId")
                        .IsUnique()
                        .HasDatabaseName("IX_supplier_invoices_posted_actual_cost_id")
                        .HasFilter("posted_actual_cost_id IS NOT NULL");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "DueDate");

                    b.HasIndex("ProjectId", "SupplierKey", "InvoiceNumberKey")
                        .IsUnique();

                    b.ToTable("supplier_invoices", null, t =>
                        {
                            t.HasCheckConstraint("CK_supplier_invoices_posting_pair", "(posted_actual_cost_id IS NULL AND posted_at_utc IS NULL) OR (posted_actual_cost_id IS NOT NULL AND posted_at_utc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BusinessOS.Modules.Budgeting.Domain.BudgetLine", b =>
                {
                    b.HasOne("BusinessOS.Modules.Budgeting.Domain.BudgetVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessOS.Modules.Budgeting.Domain.BudgetVersion", b =>
                {
                    b.HasOne("BusinessOS.Modules.Budgeting.Domain.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessOS.Modules.Budgeting.Domain.SupplierInvoice", b =>
                {
                    b.HasOne("BusinessOS.Modules.Budgeting.Domain.ActualCost", null)
                        .WithMany()
                        .HasForeignKey("PostedActualCostId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
