using BusinessOS.Modules.Budgeting.Application;
using BusinessOS.Modules.Budgeting.Domain;
using FluentAssertions;
using Xunit;
namespace BusinessOS.UnitTests;

public sealed class BudgetForecastTests
{
    private readonly Guid p = Guid.NewGuid(), b = Guid.NewGuid(), v = Guid.NewGuid();
    [Theory]
    [InlineData(100, 40, 30, 70, 30, "70", BudgetForecastState.UnderBudget)]
    [InlineData(100, 70, 30, 100, 0, "100", BudgetForecastState.OnBudget)]
    [InlineData(100, 80, 40, 120, -20, "120", BudgetForecastState.OverBudget)]
    [InlineData(0, 10, 5, 15, -15, null, BudgetForecastState.UnplannedSpend)]
    [InlineData(0, 0, 0, 0, 0, null, BudgetForecastState.OnBudget)]
    public async Task Eac_formula(decimal plan, decimal actual, decimal etc, decimal eac, decimal vac, string? utilizationText, BudgetForecastState state)
    { var x = (await Service(Store([new(BudgetLineKind.Capex, plan, "PLN")], [new(ActualCostKind.Capex, actual, "PLN")], [new(ForecastCostKind.Capex, etc, "PLN")])).GetSnapshotAsync(p, b, v, default))!.Capex; decimal? utilization = utilizationText is null ? null : decimal.Parse(utilizationText, System.Globalization.CultureInfo.InvariantCulture); x.Should().Be(new BudgetForecastMetric(plan, actual, etc, eac, vac, utilization, state)); }
    [Fact] public async Task Totals_are_recomputed_with_full_precision_and_non_expenses_are_ignored() { var x = (await Service(Store([new(BudgetLineKind.Capex, 3, "PLN"), new(BudgetLineKind.Opex, 7, "PLN"), new(BudgetLineKind.Revenue, 99, "PLN"), new(BudgetLineKind.Financing, 99, "PLN")], [new(ActualCostKind.Capex, 1, "PLN")], [new(ForecastCostKind.Opex, 2, "PLN")])).GetSnapshotAsync(p, b, v, default))!; x.Total.Should().Be(new BudgetForecastMetric(10, 1, 2, 3, 7, 30, BudgetForecastState.UnderBudget)); x.Capex.EacUtilizationPercent.Should().Be(1m / 3m * 100); }
    [Theory][InlineData(0)][InlineData(1)][InlineData(2)] public async Task Every_source_currency_is_validated(int source) { var lines = new[] { new BudgetForecastLineSource(BudgetLineKind.Capex, 1, source == 0 ? "EUR" : "PLN") }; var actual = new[] { new BudgetForecastActualSource(ActualCostKind.Capex, 1, source == 1 ? "EUR" : "PLN") }; var forecasts = new[] { new BudgetForecastCostSource(ForecastCostKind.Capex, 1, source == 2 ? "EUR" : "PLN") }; await Assert.ThrowsAsync<BudgetForecastReadException>(() => Service(Store(lines, actual, forecasts)).GetSnapshotAsync(p, b, v, default)); }
    [Fact] public async Task Null_scope_is_preserved() { var s = Store([], [], []); s.Source = null; (await Service(s).GetSnapshotAsync(p, b, v, default)).Should().BeNull(); }
    [Fact] public async Task Cancellation_is_preserved() { using var c = new CancellationTokenSource(); c.Cancel(); await Assert.ThrowsAnyAsync<OperationCanceledException>(() => Service(Store([], [], [])).GetSnapshotAsync(p, b, v, c.Token)); }
    [Fact] public async Task Technical_failure_is_safe() { var s = new FakeStore { Failure = new Exception("sqlite secret") }; var e = await Assert.ThrowsAsync<BudgetForecastReadException>(() => Service(s).ListBudgetsAsync(p, default)); e.Message.Should().NotContain("secret"); }
    [Fact] public async Task Lists_delegate_and_preserve_results() { var s = Store([], [], []); s.Budgets = [new(Guid.NewGuid(), "B", BudgetStatus.Archived, DateTimeOffset.UtcNow)]; s.Versions = [new(Guid.NewGuid(), b, 2, DateTimeOffset.UtcNow)]; (await Service(s).ListBudgetsAsync(p, default)).Should().BeSameAs(s.Budgets); (await Service(s).ListVersionsAsync(b, default)).Should().BeSameAs(s.Versions); }
    [Fact] public async Task Missing_project_returns_null() { (await new BudgetForecastQueryService(Store([], [], []), new Projects(Guid.NewGuid())).GetSnapshotAsync(p, b, v, default)).Should().BeNull(); }
    [Fact] public async Task Unavailable_project_returns_null() { (await new BudgetForecastQueryService(Store([], [], []), new Projects(p, false)).GetSnapshotAsync(p, b, v, default)).Should().BeNull(); }
    [Theory][InlineData(10, 0)][InlineData(0, 10)][InlineData(10, 10)] public async Task Actual_forecast_and_combination_are_supported(decimal actual, decimal forecast) { var x = (await Service(Store([], [new(ActualCostKind.Opex, actual, "PLN")], [new(ForecastCostKind.Opex, forecast, "PLN")])).GetSnapshotAsync(p, b, v, default))!.Opex; x.EstimateAtCompletion.Should().Be(actual + forecast); x.State.Should().Be(BudgetForecastState.UnplannedSpend); }
    [Fact] public async Task Currency_comparison_is_case_insensitive() { (await Service(Store([new(BudgetLineKind.Capex, 1, "pln")], [], [])).GetSnapshotAsync(p, b, v, default)).Should().NotBeNull(); }
    [Theory][InlineData("budgets")][InlineData("versions")][InlineData("snapshot")] public async Task Every_technical_read_failure_is_safe(string operation) { var s = Store([], [], []); s.Failure = new InvalidOperationException("provider secret"); Func<Task> read = operation == "budgets" ? async () => await Service(s).ListBudgetsAsync(p, default) : operation == "versions" ? async () => await Service(s).ListVersionsAsync(b, default) : async () => await Service(s).GetSnapshotAsync(p, b, v, default); var e = await Assert.ThrowsAsync<BudgetForecastReadException>(read); e.Message.Should().NotContain("secret"); }
    [Theory][InlineData("budgets")][InlineData("versions")][InlineData("snapshot")] public async Task Every_read_preserves_cancellation(string operation) { using var c = new CancellationTokenSource(); c.Cancel(); Func<Task> read = operation == "budgets" ? async () => await Service(Store([], [], [])).ListBudgetsAsync(p, c.Token) : operation == "versions" ? async () => await Service(Store([], [], [])).ListVersionsAsync(b, c.Token) : async () => await Service(Store([], [], [])).GetSnapshotAsync(p, b, v, c.Token); await Assert.ThrowsAnyAsync<OperationCanceledException>(read); }
    private BudgetForecastQueryService Service(FakeStore s) => new(s, new Projects(p));
    private FakeStore Store(IReadOnlyList<BudgetForecastLineSource> l, IReadOnlyList<BudgetForecastActualSource> a, IReadOnlyList<BudgetForecastCostSource> f) => new() { Source = new(p, b, "Plan", BudgetStatus.Archived, v, 1, l, a, f) };
    private sealed class Projects(Guid id, bool available = true) : IBudgetingProjectLookup { public Task<BudgetProjectInfo?> GetAsync(Guid x, CancellationToken c) => Task.FromResult<BudgetProjectInfo?>(x == id ? new(id, "Project", "PLN", available) : null); public Task<IReadOnlyList<BudgetProjectInfo>> ListAvailableAsync(CancellationToken c) => Task.FromResult((IReadOnlyList<BudgetProjectInfo>)[]); }
    private sealed class FakeStore : IBudgetForecastReadStore { public IReadOnlyList<BudgetForecastBudgetItem> Budgets { get; set; } = []; public IReadOnlyList<BudgetForecastVersionItem> Versions { get; set; } = []; public BudgetForecastSnapshotSource? Source { get; set; } public Exception? Failure { get; set; } public Task<IReadOnlyList<BudgetForecastBudgetItem>> ListBudgetsAsync(Guid x, CancellationToken c) => Failure is null ? Task.FromResult(Budgets) : Task.FromException<IReadOnlyList<BudgetForecastBudgetItem>>(Failure); public Task<IReadOnlyList<BudgetForecastVersionItem>> ListVersionsAsync(Guid x, CancellationToken c) => Failure is null ? Task.FromResult(Versions) : Task.FromException<IReadOnlyList<BudgetForecastVersionItem>>(Failure); public Task<BudgetForecastSnapshotSource?> GetSnapshotSourceAsync(Guid x, Guid y, Guid z, CancellationToken c) => Failure is null ? Task.FromResult(Source) : Task.FromException<BudgetForecastSnapshotSource?>(Failure); }
}
