using BusinessOS.Desktop.ViewModels;
using BusinessOS.Modules.Budgeting.Application;
using BusinessOS.Modules.Budgeting.Domain;
using FluentAssertions;
using Xunit;

namespace BusinessOS.UnitTests;

public sealed class BudgetingViewModelTests
{
    private static BudgetProjectInfo Project(Guid? id = null) => new(id ?? Guid.NewGuid(), "Gym", "PLN", true);
    private static BudgetItem Budget(Guid project, int latest = 0, BudgetStatus status = BudgetStatus.Draft, string name = "Plan", long version = 1, Guid? id = null) => new(id ?? Guid.NewGuid(), project, name, status, DateTimeOffset.UtcNow, version, latest);
    private static BudgetLineItem Line(Guid version, BudgetLineKind kind, decimal amount, string name = "Line", Guid? id = null) => new(id ?? Guid.NewGuid(), version, kind, name, amount, "PLN", 1, null);
    private static BudgetVersionItem Version(Guid budget, int number, IReadOnlyList<BudgetLineItem>? lines = null, Guid? id = null) { var vid = id ?? Guid.NewGuid(); return new(vid, budget, number, DateTimeOffset.UtcNow, null, lines ?? []); }

    [Fact] public async Task Initial_load_and_project_selection_present_empty_state() { var p = Project(); var vm = new BudgetingViewModel(new FakeCrud(), new FakeLookup { Items = [p] }); await vm.InitializeAsync(); vm.Projects.Should().Equal(p); await vm.SelectProjectAsync(p); vm.SelectedProject.Should().Be(p); vm.IsEmpty.Should().BeTrue(); }
    [Fact] public async Task ReloadProjects_preserves_selected_project_and_reloads_its_budgets() { var p = Project(); var crud = new FakeCrud(); var vm = new BudgetingViewModel(crud, new FakeLookup { Items = [p] }); await vm.InitializeAsync(); await vm.SelectProjectAsync(p); var b = Budget(p.Id); crud.Budgets = [b]; await vm.ReloadProjectsAsync(); vm.SelectedProject!.Id.Should().Be(p.Id); vm.Budgets.Should().Equal(b); vm.IsEmpty.Should().BeFalse(); }
    [Fact] public async Task ReloadProjects_clears_project_and_data_when_project_disappears() { var p = Project(); var lookup = new FakeLookup { Items = [p] }; var crud = new FakeCrud { Budgets = [Budget(p.Id)] }; var vm = new BudgetingViewModel(crud, lookup); await vm.InitializeAsync(); await vm.SelectProjectAsync(p); lookup.Items = []; await vm.ReloadProjectsAsync(); vm.SelectedProject.Should().BeNull(); vm.Budgets.Should().BeEmpty(); }
    [Fact] public async Task Project_selection_failure_rolls_back_and_notifies_selection() { var a = Project(); var b = Project(); var crud = new FakeCrud(); var vm = new BudgetingViewModel(crud, new FakeLookup { Items = [a, b] }); await vm.InitializeAsync(); await vm.SelectProjectAsync(a); var notified = 0; vm.PropertyChanged += (_, e) => { if (e.PropertyName == nameof(vm.SelectedProject)) notified++; }; crud.FailReads = true; await vm.SelectProjectAsync(b); vm.SelectedProject.Should().Be(a); vm.Budgets.Should().BeEmpty(); notified.Should().BePositive(); vm.OperationMessage.Should().Contain("Nie udało"); }
    [Fact] public async Task Create_and_rename_preserve_programmatic_budget_selection() { var p = Project(); var crud = new FakeCrud(); var vm = new BudgetingViewModel(crud, new FakeLookup { Items = [p] }); await vm.InitializeAsync(); await vm.SelectProjectAsync(p); vm.BeginCreateBudget(); vm.BudgetName = "First"; await vm.SaveBudgetAsync(); vm.SelectedBudget!.Name.Should().Be("First"); vm.BeginRenameBudget(); vm.BudgetName = "Renamed"; await vm.SaveBudgetAsync(); vm.SelectedBudget!.Name.Should().Be("Renamed"); }
    [Fact] public async Task Duplicate_and_concurrency_results_keep_safe_editor_state_and_refresh_current() { var p = Project(); var existing = Budget(p.Id, name: "Existing"); var crud = new FakeCrud { Budgets = [existing], NextStatus = BudgetingOperationStatus.DuplicateName }; var vm = await Selected(crud, p, existing); vm.BeginRenameBudget(); vm.BudgetName = "Existing"; await vm.SaveBudgetAsync(); vm.IsBudgetEditorOpen.Should().BeTrue(); vm.OperationMessage.Should().NotBeEmpty(); crud.NextStatus = BudgetingOperationStatus.ConcurrencyConflict; await vm.SaveBudgetAsync(); vm.SelectedBudget.Should().Be(existing); }
    [Fact] public async Task Initial_and_next_version_select_new_revision_and_copy_lines() { var p = Project(); var b = Budget(p.Id); var crud = new FakeCrud { Budgets = [b] }; var vm = await Selected(crud, p, b); await vm.CreateInitialVersionAsync(); vm.SelectedVersion!.Number.Should().Be(1); vm.BeginAddLine(); vm.LineName = "CAPEX"; vm.LineAmount = "100"; await vm.SaveLineAsync(); await vm.CreateNextVersionAsync(); vm.SelectedVersion!.Number.Should().Be(2); vm.Lines.Should().ContainSingle(x => x.Name == "CAPEX" && x.Amount == 100); var v1 = vm.Versions.Single(x => x.Number == 1); await vm.SelectVersionAsync(v1); vm.CanAddLine.Should().BeFalse(); }
    [Fact] public async Task Add_update_remove_lines_inherit_currency_and_recalculate_totals() { var p = Project(); var b = Budget(p.Id, 1); var v = Version(b.Id, 1); var crud = new FakeCrud { Budgets = [b], Versions = [v] }; var vm = await Selected(crud, p, b); vm.BeginAddLine(); vm.LineKind = BudgetLineKind.Revenue; vm.LineName = "Sales"; vm.LineAmount = "250"; await vm.SaveLineAsync(); crud.LastCurrency.Should().Be("PLN"); vm.RevenueTotal.Should().Be(250); vm.SelectedLine = vm.Lines.Single(); vm.BeginEditLine(); vm.LineAmount = "300"; await vm.SaveLineAsync(); vm.RevenueTotal.Should().Be(300); vm.SelectedLine = vm.Lines.Single(); await vm.RemoveSelectedLineAsync(); vm.RevenueTotal.Should().Be(0); }
    [Fact] public async Task Activation_capability_uses_latest_version_not_viewed_history() { var p = Project(); var b = Budget(p.Id, 2); var v1id = Guid.NewGuid(); var v1 = Version(b.Id, 1, [Line(v1id, BudgetLineKind.Capex, 100)], v1id); var v2 = Version(b.Id, 2); var crud = new FakeCrud { Budgets = [b], Versions = [v1, v2] }; var vm = await Selected(crud, p, b); await vm.SelectVersionAsync(v1); vm.CanActivateBudget.Should().BeFalse(); var l = Line(v2.Id, BudgetLineKind.Revenue, 1); crud.Versions = [v1, v2 with { Lines = [l] }]; await vm.RefreshAsync(); await vm.SelectVersionAsync(vm.Versions.Single(x => x.Number == 1)); vm.CanActivateBudget.Should().BeTrue(); }
    [Fact] public async Task Lifecycle_and_editors_gate_navigation_and_recovery_capabilities() { var p = Project(); var b = Budget(p.Id, 1); var vid = Guid.NewGuid(); var v = Version(b.Id, 1, [Line(vid, BudgetLineKind.Capex, 1)], vid); var crud = new FakeCrud { Budgets = [b], Versions = [v] }; var vm = await Selected(crud, p, b); vm.BeginRenameBudget(); vm.CanNavigate.Should().BeFalse(); vm.CancelBudgetEditor(); vm.BeginAddLine(); vm.CanNavigate.Should().BeFalse(); vm.CancelLineEditor(); vm.OpenActivateDialog(); vm.CanNavigate.Should().BeFalse(); vm.CloseLifecycleDialog(); vm.OpenArchiveDialog(); await vm.ArchiveSelectedBudgetAsync(); vm.Budgets.Should().BeEmpty(); }
    [Fact] public async Task Presentation_failure_is_safe() { var vm = new BudgetingViewModel(new FakeCrud(), new FakeLookup()); vm.ReportPresentationFailure(); vm.OperationMessage.Should().Be("Nie udało się wykonać operacji. Spróbuj ponownie."); await vm.InitializeAsync(); vm.CanNavigate.Should().BeTrue(); }
    [Fact]
    public async Task Budget_selection_failure_preserves_previous_budget_versions_and_lines_and_restores_binding()
    {
        var p = Project(); var first = Budget(p.Id, 1, name: "First"); var second = Budget(p.Id, 1, name: "Second");
        var firstId = Guid.NewGuid(); var secondId = Guid.NewGuid();
        var firstVersion = Version(first.Id, 1, [Line(firstId, BudgetLineKind.Capex, 10, "Old")], firstId);
        var secondVersion = Version(second.Id, 1, [Line(secondId, BudgetLineKind.Revenue, 20, "New")], secondId);
        var crud = new FakeCrud { Budgets = [first, second], Versions = [firstVersion, secondVersion] };
        var vm = await Selected(crud, p, first); var notifications = 0;
        vm.PropertyChanged += (_, e) => { if (e.PropertyName == nameof(vm.SelectedBudget)) notifications++; };
        crud.FailVersionsFor = second.Id; await vm.SelectBudgetAsync(second);
        vm.SelectedBudget.Should().Be(first); vm.Versions.Should().Equal(firstVersion); vm.SelectedVersion.Should().Be(firstVersion);
        vm.Lines.Should().ContainSingle(x => x.Name == "Old"); notifications.Should().BePositive(); vm.OperationMessage.Should().Contain("Nie udało");
    }
    [Fact]
    public async Task Refresh_version_failure_preserves_complete_budget_selection_state()
    {
        var p = Project(); var budget = Budget(p.Id, 1); var id = Guid.NewGuid(); var version = Version(budget.Id, 1, [Line(id, BudgetLineKind.Capex, 10, "Stable")], id);
        var crud = new FakeCrud { Budgets = [budget], Versions = [version] }; var vm = await Selected(crud, p, budget);
        crud.Budgets = [budget with { Name = "Partial" }]; crud.FailVersionsFor = budget.Id; await vm.RefreshAsync();
        vm.Budgets.Should().ContainSingle().Which.Name.Should().Be("Plan"); vm.SelectedBudget.Should().Be(budget);
        vm.Versions.Should().Equal(version); vm.SelectedVersion.Should().Be(version); vm.Lines.Should().ContainSingle(x => x.Name == "Stable");
    }

    private static async Task<BudgetingViewModel> Selected(FakeCrud crud, BudgetProjectInfo p, BudgetItem b) { var vm = new BudgetingViewModel(crud, new FakeLookup { Items = [p] }); await vm.InitializeAsync(); await vm.SelectProjectAsync(p); await vm.SelectBudgetAsync(b); return vm; }
    private sealed class FakeLookup : IBudgetingProjectLookup { public IReadOnlyList<BudgetProjectInfo> Items { get; set; } = []; public bool Fail { get; set; } public Task<BudgetProjectInfo?> GetAsync(Guid id, CancellationToken ct) => Task.FromResult(Items.FirstOrDefault(x => x.Id == id)); public Task<IReadOnlyList<BudgetProjectInfo>> ListAvailableAsync(CancellationToken ct) => Fail ? Task.FromException<IReadOnlyList<BudgetProjectInfo>>(new BudgetingProjectLookupException("x", new Exception())) : Task.FromResult(Items); }
    private sealed class FakeCrud : IBudgetingCrudService
    {
        public IReadOnlyList<BudgetItem> Budgets { get; set; } = []; public IReadOnlyList<BudgetVersionItem> Versions { get; set; } = []; public bool FailReads { get; set; }
        public BudgetingOperationStatus NextStatus { get; set; } = BudgetingOperationStatus.Success; public string? LastCurrency { get; private set; }
        public Guid? FailVersionsFor { get; set; }
        public Task<IReadOnlyList<BudgetItem>> ListBudgetsAsync(Guid id, CancellationToken ct) => FailReads ? Task.FromException<IReadOnlyList<BudgetItem>>(new BudgetingReadException(new Exception())) : Task.FromResult(Budgets.Where(x => x.ProjectId == id).ToArray() as IReadOnlyList<BudgetItem>);
        public Task<BudgetItem?> GetBudgetAsync(Guid id, CancellationToken ct) => Task.FromResult(Budgets.FirstOrDefault(x => x.Id == id));
        public Task<BudgetingResult<BudgetItem>> CreateBudgetAsync(Guid p, string n, CancellationToken ct) { if (NextStatus != BudgetingOperationStatus.Success) return Task.FromResult(new BudgetingResult<BudgetItem>(NextStatus, "safe", null)); var b = Budget(p, name: n); Budgets = [.. Budgets, b]; return Task.FromResult(new BudgetingResult<BudgetItem>(NextStatus, "ok", b)); }
        public Task<BudgetingResult<BudgetItem>> RenameBudgetAsync(Guid id, long version, string n, CancellationToken ct) { if (NextStatus != BudgetingOperationStatus.Success) return Task.FromResult(new BudgetingResult<BudgetItem>(NextStatus, "safe", null)); var old = Budgets.Single(x => x.Id == id); var b = old with { Name = n, Version = old.Version + 1 }; Budgets = Budgets.Select(x => x.Id == id ? b : x).ToArray(); return Task.FromResult(new BudgetingResult<BudgetItem>(NextStatus, "ok", b)); }
        public Task<BudgetingResult<BudgetItem>> ActivateBudgetAsync(Guid id, long version, CancellationToken ct) { var old = Budgets.Single(x => x.Id == id); var b = old with { Status = BudgetStatus.Active, Version = old.Version + 1 }; Budgets = Budgets.Select(x => x.Id == id ? b : x).ToArray(); return Task.FromResult(new BudgetingResult<BudgetItem>(BudgetingOperationStatus.Success, "ok", b)); }
        public Task<BudgetingResult> ArchiveBudgetAsync(Guid id, long version, CancellationToken ct) { Budgets = Budgets.Where(x => x.Id != id).ToArray(); return Task.FromResult(new BudgetingResult(BudgetingOperationStatus.Success, "ok")); }
        public Task<BudgetingResult<BudgetVersionItem>> CreateInitialVersionAsync(Guid id, long version, string? note, CancellationToken ct) => CreateVersion(id, 1, []);
        public Task<BudgetingResult<BudgetVersionItem>> CreateNextVersionAsync(Guid id, long version, string? note, CancellationToken ct) { var old = Versions.Where(x => x.BudgetId == id).MaxBy(x => x.Number)!; var vid = Guid.NewGuid(); return CreateVersion(id, old.Number + 1, old.Lines.Select(x => x with { Id = Guid.NewGuid(), VersionId = vid }).ToArray(), vid); }
        private Task<BudgetingResult<BudgetVersionItem>> CreateVersion(Guid bid, int number, IReadOnlyList<BudgetLineItem> lines, Guid? id = null) { var v = Version(bid, number, lines, id); Versions = [.. Versions, v]; Budgets = Budgets.Select(x => x.Id == bid ? x with { LatestVersion = number, Version = x.Version + 1 } : x).ToArray(); return Task.FromResult(new BudgetingResult<BudgetVersionItem>(BudgetingOperationStatus.Success, "ok", v)); }
        public Task<BudgetVersionItem?> GetVersionAsync(Guid id, CancellationToken ct) => Task.FromResult(Versions.FirstOrDefault(x => x.Id == id)); public Task<IReadOnlyList<BudgetVersionItem>> ListVersionsAsync(Guid id, CancellationToken ct) => FailVersionsFor == id ? Task.FromException<IReadOnlyList<BudgetVersionItem>>(new BudgetingReadException(new Exception())) : Task.FromResult(Versions.Where(x => x.BudgetId == id).ToArray() as IReadOnlyList<BudgetVersionItem>);
        public Task<BudgetingResult<BudgetLineItem>> AddLineAsync(Guid vid, BudgetLineKind k, string n, decimal a, string c, int o, string? note, CancellationToken ct) { LastCurrency = c; var l = new BudgetLineItem(Guid.NewGuid(), vid, k, n, a, c, o, note); Versions = Versions.Select(x => x.Id == vid ? x with { Lines = [.. x.Lines, l] } : x).ToArray(); return Task.FromResult(new BudgetingResult<BudgetLineItem>(BudgetingOperationStatus.Success, "ok", l)); }
        public Task<BudgetingResult<BudgetLineItem>> UpdateLineAsync(Guid id, BudgetLineKind k, string n, decimal a, string c, int o, string? note, CancellationToken ct) { LastCurrency = c; BudgetLineItem? updated = null; Versions = Versions.Select(v => v with { Lines = v.Lines.Select(x => x.Id == id ? (updated = new(id, x.VersionId, k, n, a, c, o, note)) : x).ToArray() }).ToArray(); return Task.FromResult(new BudgetingResult<BudgetLineItem>(BudgetingOperationStatus.Success, "ok", updated)); }
        public Task<BudgetingResult> RemoveLineAsync(Guid id, CancellationToken ct) { Versions = Versions.Select(v => v with { Lines = v.Lines.Where(x => x.Id != id).ToArray() }).ToArray(); return Task.FromResult(new BudgetingResult(BudgetingOperationStatus.Success, "ok")); }
    }
}
