using BusinessOS.BuildingBlocks.Domain.Ids;
using BusinessOS.Modules.BusinessProjects.Application;
using BusinessOS.Modules.BusinessProjects.Domain;
using FluentAssertions;
using Microsoft.Extensions.DependencyInjection;
using Xunit;
namespace BusinessOS.UnitTests;

public sealed class BusinessProjectsApplicationTests
{
    [Fact] public async Task List_forwards_company_and_status_and_maps_result() { var p = Project(); var store = new Store { Listed = [p] }; var access = new Access { Company = Company(p.CompanyId.Value) }; var result = await Create(store, access).ListAsync(p.CompanyId.Value, BusinessProjectStatusValue.Draft, default); result.Should().ContainSingle(x => x.Id == p.Id.Value); store.Status.Should().Be(BusinessProjectStatus.Draft); }
    [Fact] public async Task List_unavailable_is_empty_and_does_not_query_store() { var store = new Store(); (await Create(store, new Access()).ListAsync(Guid.NewGuid(), null, default)).Should().BeEmpty(); store.Calls.Should().NotContain("list"); }
    [Fact] public async Task List_failures_are_controlled_and_cancellation_propagates() { var store = new Store { ListException = Failure() }; var service = Create(store, new Access { Company = Company(Guid.NewGuid()) }); await FluentActions.Invoking(() => service.ListAsync(Guid.NewGuid(), null, default)).Should().ThrowAsync<BusinessProjectsReadException>(); var token = new CancellationToken(true); await FluentActions.Invoking(() => service.ListAsync(Guid.NewGuid(), null, token)).Should().ThrowAsync<OperationCanceledException>(); }
    [Fact] public async Task Undefined_list_status_is_controlled() { var service = Create(new Store(), new Access { Company = Company(Guid.NewGuid()) }); await FluentActions.Invoking(() => service.ListAsync(Guid.NewGuid(), (BusinessProjectStatusValue)999, default)).Should().ThrowAsync<BusinessProjectsReadException>(); }
    [Fact] public async Task Get_covers_success_missing_and_inaccessible() { var p = Project(); var store = new Store { Entity = p }; (await Create(store, new Access { Company = Company(p.CompanyId.Value) }).GetAsync(p.Id.Value, default))!.Id.Should().Be(p.Id.Value); (await Create(new Store(), new Access()).GetAsync(Guid.NewGuid(), default)).Should().BeNull(); (await Create(store, new Access()).GetAsync(p.Id.Value, default)).Should().BeNull(); }
    [Fact] public async Task Get_store_and_lookup_failures_are_controlled() { var p = Project(); await FluentActions.Invoking(() => Create(new Store { GetException = Failure() }, new Access()).GetAsync(p.Id.Value, default)).Should().ThrowAsync<BusinessProjectsReadException>(); await FluentActions.Invoking(() => Create(new Store { Entity = p }, new Access { Exception = AccessFailure() }).GetAsync(p.Id.Value, default)).Should().ThrowAsync<BusinessProjectsReadException>(); }
    [Theory]
    [InlineData("name")]
    [InlineData("type")]
    [InlineData("location")]
    [InlineData("currency")]
    [InlineData("long-currency")]
    [InlineData("opening")]
    [InlineData("companyId")]
    public async Task Create_validation_reports_exact_field_without_reaching_persistence(string invalidField)
    {
        var companyId = invalidField == "companyId" ? Guid.Empty : Guid.NewGuid();
        var request = new CreateBusinessProjectRequest(companyId,
            invalidField == "name" ? "" : "P",
            invalidField == "type" ? "" : "Gym",
            invalidField == "location" ? "" : "L",
            "", new(2026, 1, 1), invalidField == "opening" ? new(2025, 12, 31) : new(2026, 2, 1),
            invalidField switch { "currency" => "", "long-currency" => "EURO", _ => "PLN" });
        var store = new Store();
        var result = await Create(store, new Access { Company = Company(companyId) }).CreateAsync(request, default);
        result.Status.Should().Be(BusinessProjectOperationStatus.ValidationFailed);
        var expectedKey = invalidField switch { "type" => "type", "long-currency" or "currency" => "value", _ => invalidField };
        result.ValidationErrors.Should().ContainKey(expectedKey);
        result.SafeMessage.Should().NotContain("Exception").And.NotContain("Argument");
        store.Calls.Should().NotContain(["add", "save"]);
        store.Resets.Should().Be(1);
    }
    [Fact] public async Task Create_success_duplicate_and_save_races_reset_tracking() { var company = Guid.NewGuid(); var store = new Store(); var service = Create(store, new Access { Company = Company(company) }); (await service.CreateAsync(Request(company), default)).Status.Should().Be(BusinessProjectOperationStatus.Success); store.Resets.Should().BeGreaterThanOrEqualTo(1); store = new Store { Exists = true }; (await Create(store, new Access { Company = Company(company) }).CreateAsync(Request(company), default)).Status.Should().Be(BusinessProjectOperationStatus.DuplicateProjectName); store.Resets.Should().Be(1); foreach (var pair in new[] { (BusinessProjectsSaveStatus.DuplicateProjectName, BusinessProjectOperationStatus.DuplicateProjectName), (BusinessProjectsSaveStatus.ConcurrencyConflict, BusinessProjectOperationStatus.ConcurrencyConflict) }) { store = new() { Save = pair.Item1 }; (await Create(store, new Access { Company = Company(company) }).CreateAsync(Request(company), default)).Status.Should().Be(pair.Item2); store.Resets.Should().BeGreaterThanOrEqualTo(1); } }
    [Fact] public async Task Create_persistence_lookup_and_cancellation_are_safe() { var company = Guid.NewGuid(); foreach (var store in new[] { new Store { AddException = Failure() }, new Store { SaveException = Failure() } }) { var result = await Create(store, new Access { Company = Company(company) }).CreateAsync(Request(company), default); result.Status.Should().Be(BusinessProjectOperationStatus.PersistenceFailure); store.Resets.Should().Be(1); } var lookupStore = new Store(); (await Create(lookupStore, new Access { Exception = AccessFailure() }).CreateAsync(Request(company), default)).Status.Should().Be(BusinessProjectOperationStatus.PersistenceFailure); lookupStore.Resets.Should().Be(1); var cancelled = new Store(); (await Create(cancelled, new Access { Company = Company(company) }).CreateAsync(Request(company), new(true))).Status.Should().Be(BusinessProjectOperationStatus.Cancelled); cancelled.Resets.Should().Be(1); }
    [Fact] public async Task Update_checks_access_before_version_and_does_not_mutate_on_early_returns() { var p = Project(); var original = (p.Name, p.Version.Value); var store = new Store { Entity = p }; var access = new Access(); var unavailable = await Create(store, access).UpdateAsync(Update(p, 999), default); unavailable.Status.Should().Be(BusinessProjectOperationStatus.CompanyNotFound); (p.Name, p.Version.Value).Should().Be(original); store.Calls.Should().ContainInOrder("get", "reset"); access.Calls.Should().Equal("access"); store = new() { Entity = p }; var stale = await Create(store, new Access { Company = Company(p.CompanyId.Value) }).UpdateAsync(Update(p, 999), default); stale.Status.Should().Be(BusinessProjectOperationStatus.ConcurrencyConflict); (p.Name, p.Version.Value).Should().Be(original); store.Resets.Should().Be(1); }
    [Fact] public async Task Update_success_duplicate_concurrency_and_failure_are_mapped() { foreach (var state in new[] { BusinessProjectsSaveStatus.Success, BusinessProjectsSaveStatus.DuplicateProjectName, BusinessProjectsSaveStatus.ConcurrencyConflict }) { var p = Project(); var store = new Store { Entity = p, Save = state }; var result = await Create(store, new Access { Company = Company(p.CompanyId.Value) }).UpdateAsync(Update(p, p.Version.Value), default); result.Status.Should().Be(state switch { BusinessProjectsSaveStatus.Success => BusinessProjectOperationStatus.Success, BusinessProjectsSaveStatus.DuplicateProjectName => BusinessProjectOperationStatus.DuplicateProjectName, _ => BusinessProjectOperationStatus.ConcurrencyConflict }); store.Resets.Should().BeGreaterThanOrEqualTo(1); } }
    [Fact] public async Task Status_paths_preserve_entity_on_failure_and_reset() { var p = Project(); foreach (var target in new[] { BusinessProjectStatusValue.Draft, BusinessProjectStatusValue.Operating, (BusinessProjectStatusValue)999 }) { var store = new Store { Entity = p }; var before = (p.Status, p.Version.Value); var result = await Create(store, new Access { Company = Company(p.CompanyId.Value) }).ChangeStatusAsync(new(p.Id.Value, p.Version.Value, target), default); result.Status.Should().Be(target == (BusinessProjectStatusValue)999 ? BusinessProjectOperationStatus.ValidationFailed : BusinessProjectOperationStatus.InvalidStatusTransition); (p.Status, p.Version.Value).Should().Be(before); store.Resets.Should().Be(1); } }
    [Fact] public async Task Status_success_and_save_results_are_mapped() { foreach (var state in Enum.GetValues<BusinessProjectsSaveStatus>()) { var p = Project(); var store = new Store { Entity = p, Save = state }; var result = await Create(store, new Access { Company = Company(p.CompanyId.Value) }).ChangeStatusAsync(new(p.Id.Value, p.Version.Value, BusinessProjectStatusValue.Analysis), default); result.Status.Should().Be(state switch { BusinessProjectsSaveStatus.Success => BusinessProjectOperationStatus.Success, BusinessProjectsSaveStatus.ConcurrencyConflict => BusinessProjectOperationStatus.ConcurrencyConflict, _ => BusinessProjectOperationStatus.DuplicateProjectName }); store.Resets.Should().BeGreaterThanOrEqualTo(1); } }
    [Fact] public async Task Archive_maps_all_results_without_mutating_on_early_return() { var p = Project(); foreach (var state in new[] { BusinessProjectsSaveStatus.Success, BusinessProjectsSaveStatus.ConcurrencyConflict }) { var entity = Project(); var store = new Store { Entity = entity, Save = state }; var result = await Create(store, new Access { Company = Company(entity.CompanyId.Value) }).ArchiveAsync(new(entity.Id.Value, entity.Version.Value), default); result.Status.Should().Be(state == BusinessProjectsSaveStatus.Success ? BusinessProjectOperationStatus.Success : BusinessProjectOperationStatus.ConcurrencyConflict); store.Resets.Should().BeGreaterThanOrEqualTo(1); } var staleStore = new Store { Entity = p }; var before = p.Version.Value; (await Create(staleStore, new Access { Company = Company(p.CompanyId.Value) }).ArchiveAsync(new(p.Id.Value, 999), default)).Status.Should().Be(BusinessProjectOperationStatus.ConcurrencyConflict); p.IsDeleted.Should().BeFalse(); p.Version.Value.Should().Be(before); staleStore.Resets.Should().Be(1); }
    [Fact] public async Task Get_cancellation_at_store_and_access_is_propagated() { var p = Project(); var cts = new CancellationTokenSource(); await FluentActions.Invoking(() => Create(new Store { Entity = p, CancelGet = true, Cancellation = cts }, new Access()).GetAsync(p.Id.Value, cts.Token)).Should().ThrowAsync<OperationCanceledException>(); cts = new(); await FluentActions.Invoking(() => Create(new Store { Entity = p }, new Access { Cancel = true, Cancellation = cts }).GetAsync(p.Id.Value, cts.Token)).Should().ThrowAsync<OperationCanceledException>(); }
    [Fact] public async Task Create_unavailable_and_stage_cancellations_stop_at_the_expected_operation() { var company = Guid.NewGuid(); var unavailableStore = new Store(); (await Create(unavailableStore, new Access()).CreateAsync(Request(company), default)).Status.Should().Be(BusinessProjectOperationStatus.CompanyNotFound); unavailableStore.Calls.Should().Equal("reset"); foreach (var stage in new[] { "access", "exists", "add", "save" }) { var cts = new CancellationTokenSource(); var store = new Store { Cancellation = cts, CancelNameExists = stage == "exists", CancelAdd = stage == "add", CancelSave = stage == "save" }; var access = new Access { Company = Company(company), Cancellation = cts, Cancel = stage == "access" }; var result = await Create(store, access).CreateAsync(Request(company), cts.Token); result.Status.Should().Be(BusinessProjectOperationStatus.Cancelled); store.Resets.Should().Be(1); var reached = store.Calls.Where(x => x != "reset").ToArray(); reached.LastOrDefault().Should().Be(stage == "access" ? null : stage); } }
    [Fact] public async Task Update_missing_duplicate_and_failures_do_not_mutate_before_save() { var missing = new Store(); (await Create(missing, new Access()).UpdateAsync(new(Guid.NewGuid(), 1, "P", "Gym", "L", "", new(2026, 1, 1), new(2026, 2, 1), "PLN"), default)).Status.Should().Be(BusinessProjectOperationStatus.ProjectNotFound); missing.Resets.Should().Be(1); foreach (var stage in new[] { "exists", "get", "access" }) { var p = Project(); var snapshot = Snapshot(p); var store = new Store { Entity = p, Exists = stage == "exists", GetException = stage == "get" ? Failure() : null, NameExistsException = null }; if (stage == "exists") store.Exists = true; var access = new Access { Company = Company(p.CompanyId.Value), Exception = stage == "access" ? AccessFailure() : null }; var result = await Create(store, access).UpdateAsync(Update(p, p.Version.Value), default); result.Status.Should().Be(stage == "exists" ? BusinessProjectOperationStatus.DuplicateProjectName : BusinessProjectOperationStatus.PersistenceFailure); Snapshot(p).Should().Be(snapshot); store.Resets.Should().Be(1); } }
    [Fact] public async Task Status_and_archive_missing_access_and_persistence_paths_reset_without_early_mutation() { foreach (var operation in new[] { "status", "archive" }) { foreach (var stage in new[] { "missing", "unavailable", "access", "get" }) { var p = Project(); var before = (p.Status, p.IsDeleted, p.Version.Value); var store = new Store { Entity = stage == "missing" ? null : p, GetException = stage == "get" ? Failure() : null }; var access = new Access { Company = stage == "unavailable" ? null : Company(p.CompanyId.Value), Exception = stage == "access" ? AccessFailure() : null }; var service = Create(store, access); var result = operation == "status" ? (await service.ChangeStatusAsync(new(p.Id.Value, p.Version.Value, BusinessProjectStatusValue.Analysis), default)).Status : (await service.ArchiveAsync(new(p.Id.Value, p.Version.Value), default)).Status; result.Should().NotBe(BusinessProjectOperationStatus.Success); (p.Status, p.IsDeleted, p.Version.Value).Should().Be(before); store.Resets.Should().Be(1); } } }

    private static IBusinessProjectsCrudService Create(Store store, Access access) { store.Access = access; var services = new ServiceCollection(); services.AddBusinessProjectsModule(); services.AddSingleton<IBusinessProjectsStore>(store); services.AddSingleton<IBusinessProjectCompanyAccess>(access); services.AddSingleton<IBusinessProjectsExecutionContext>(new Context()); services.AddSingleton(TimeProvider.System); return services.BuildServiceProvider().GetRequiredService<IBusinessProjectsCrudService>(); }
    private static CreateBusinessProjectRequest Request(Guid company) => new(company, "P", "Gym", "L", "", new(2026, 1, 1), new(2026, 2, 1), "PLN");
    private static UpdateBusinessProjectRequest Update(BusinessProject p, long version) => new(p.Id.Value, version, "Updated", "Retail", "Warsaw", "Description", new(2026, 3, 1), new(2026, 4, 1), "EUR");
    private static BusinessProjectCompanyInfo Company(Guid id) => new(id, "Company", "PLN");
    private static BusinessProjectsPersistenceException Failure() => new("safe", new InvalidOperationException("technical"));
    private static BusinessProjectCompanyAccessException AccessFailure() => new("safe", new InvalidOperationException("technical"));
    private static BusinessProject Project() => BusinessProject.Create(new(Guid.NewGuid()), "P", "Gym", "L", "", new(2026, 1, 1), new(2026, 2, 1), new("PLN"), new(Guid.NewGuid()), DateTimeOffset.UtcNow);
    private static object Snapshot(BusinessProject p) => new { p.Name, p.BusinessType, p.Location, p.Description, p.PlannedStartDate, p.PlannedOpeningDate, Currency = p.BaseCurrency.Value, p.UpdatedAt, UpdatedBy = p.UpdatedBy.Value, Version = p.Version.Value };
    private sealed class Context : IBusinessProjectsExecutionContext { public UserId UserId { get; } = new(Guid.NewGuid()); }
    private sealed class Access : IBusinessProjectCompanyAccess { public BusinessProjectCompanyInfo? Company { get; set; } public Exception? Exception { get; set; } public bool Cancel { get; set; } public CancellationTokenSource? Cancellation { get; set; } public List<string> Calls { get; } = []; public Task<BusinessProjectCompanyInfo?> GetAccessibleCompanyAsync(Guid id, CancellationToken ct) { Calls.Add("access"); if (Cancel) { Cancellation!.Cancel(); throw new OperationCanceledException(ct); } ct.ThrowIfCancellationRequested(); if (Exception is not null) throw Exception; return Task.FromResult(Company); } }
    private sealed class Store : IBusinessProjectsStore { public Access? Access { get; set; } public BusinessProject? Entity { get; set; } public IReadOnlyList<BusinessProject> Listed { get; set; } = []; public bool Exists { get; set; } public BusinessProjectsSaveStatus Save { get; set; } = BusinessProjectsSaveStatus.Success; public Exception? ListException { get; set; } public Exception? GetException { get; set; } public Exception? NameExistsException { get; set; } public Exception? AddException { get; set; } public Exception? SaveException { get; set; } public bool CancelList { get; set; } public bool CancelGet { get; set; } public bool CancelNameExists { get; set; } public bool CancelAdd { get; set; } public bool CancelSave { get; set; } public CancellationTokenSource? Cancellation { get; set; } public int Resets { get; set; } public BusinessProjectStatus? Status { get; set; } public List<string> Calls { get; } = []; private void CancelIf(bool cancel, CancellationToken ct) { if (!cancel) return; Cancellation!.Cancel(); throw new OperationCanceledException(ct); } public Task<IReadOnlyList<BusinessProject>> ListAsync(CompanyId id, BusinessProjectStatus? s, CancellationToken ct) { Calls.Add("list"); CancelIf(CancelList, ct); ct.ThrowIfCancellationRequested(); if (ListException is not null) throw ListException; Status = s; return Task.FromResult(Listed); } public Task<BusinessProject?> GetAsync(BusinessProjectId id, bool tracked, CancellationToken ct) { Calls.Add("get"); CancelIf(CancelGet, ct); ct.ThrowIfCancellationRequested(); if (GetException is not null) throw GetException; return Task.FromResult(Entity); } public Task<bool> NameExistsAsync(CompanyId id, string n, BusinessProjectId? e, CancellationToken ct) { Calls.Add("exists"); CancelIf(CancelNameExists, ct); ct.ThrowIfCancellationRequested(); if (NameExistsException is not null) throw NameExistsException; return Task.FromResult(Exists); } public Task<bool> HasActiveProjectsAsync(CompanyId id, CancellationToken ct) => Task.FromResult(false); public Task AddAsync(BusinessProject p, CancellationToken ct) { Calls.Add("add"); CancelIf(CancelAdd, ct); ct.ThrowIfCancellationRequested(); if (AddException is not null) throw AddException; Entity = p; return Task.CompletedTask; } public Task<BusinessProjectsSaveStatus> SaveChangesAsync(CancellationToken ct) { Calls.Add("save"); CancelIf(CancelSave, ct); ct.ThrowIfCancellationRequested(); if (SaveException is not null) throw SaveException; return Task.FromResult(Save); } public Task ResetTrackingAsync() { Calls.Add("reset"); Resets++; return Task.CompletedTask; } }
}
