using BusinessOS.Desktop.ViewModels;
using BusinessOS.Modules.BusinessProjects.Application;
using BusinessOS.Modules.Companies.Application;
using BusinessOS.Modules.Budgeting.Application;
using FluentAssertions;
using Xunit;
namespace BusinessOS.UnitTests;

public sealed class BusinessProjectsWorkspaceTests
{
    private static CompanyLookupItem Company(Guid? id = null) => new(id ?? Guid.NewGuid(), "Firma", "PLN", CompanyStatusValue.Active);
    private static BusinessProjectListItem Project(BusinessProjectStatusValue status = BusinessProjectStatusValue.Draft, Guid? id = null, long version = 1) => new(id ?? Guid.NewGuid(), Guid.NewGuid(), "Projekt", "Gym", "Lodz", status, new(2026, 1, 1), new(2026, 2, 1), "PLN", DateTimeOffset.UtcNow, version);
    private static BusinessProjectDetails Details(BusinessProjectListItem p, params BusinessProjectStatusValue[] allowed) => new(p.Id, p.CompanyId, p.Name, p.BusinessType, p.Location, "", p.Status, p.PlannedStartDate, p.PlannedOpeningDate, p.BaseCurrency, DateTimeOffset.UtcNow, p.UpdatedAtUtc, Guid.NewGuid(), Guid.NewGuid(), p.Version, allowed);
    private static BudgetingViewModel Budget() => new(new FakeBudgeting(), new FakeBudgetLookup());
    private static ActualCostsViewModel Actual() => new(new FakeActualCosts(), new FakeBudgetLookup(), TimeProvider.System);
    private static BudgetVarianceViewModel Variance(FakeBudgetLookup? lookup = null, FakeVariance? service = null) => new(service ?? new(), lookup ?? new());
    [Fact] public async Task Reload_companies_selects_single_company_and_loads_projects() { var c = Company(); var crud = new FakeProjects { Listed = [Project()] }; var vm = new BusinessProjectsViewModel(crud, new FakeLookup { Items = [c] }, TimeProvider.System); await vm.ReloadCompaniesAsync(); vm.SelectedCompany!.Id.Should().Be(c.Id); vm.Projects.Should().HaveCount(1); vm.LastCompaniesReloadSucceeded.Should().BeTrue(); }
    [Fact] public async Task Reload_preserves_existing_company_and_clears_removed_company() { var a = Company(); var b = Company(); var lookup = new FakeLookup { Items = [a, b] }; var vm = new BusinessProjectsViewModel(new FakeProjects(), lookup, TimeProvider.System); await vm.ReloadCompaniesAsync(); await vm.SelectCompanyAsync(a); await vm.ReloadCompaniesAsync(); vm.SelectedCompany!.Id.Should().Be(a.Id); lookup.Items = [b]; await vm.ReloadCompaniesAsync(); vm.SelectedCompany.Should().BeNull(); vm.Projects.Should().BeEmpty(); vm.OperationMessage.Should().Contain("nie jest już dostępna"); }
    [Fact] public async Task Status_button_is_available_before_transitions_are_loaded_and_terminal_projects_disable_it() { var c = Company(); var draft = Project(); var crud = new FakeProjects { Listed = [draft], Details = Details(draft, BusinessProjectStatusValue.Analysis) }; var vm = new BusinessProjectsViewModel(crud, new FakeLookup { Items = [c] }, TimeProvider.System); await vm.ReloadCompaniesAsync(); vm.SelectedProject = draft; vm.CanChangeStatus.Should().BeTrue(); await vm.OpenStatusDialogAsync(); vm.IsStatusDialogOpen.Should().BeTrue(); vm.AllowedTransitions.Should().Equal(BusinessProjectStatusValue.Analysis); vm.CloseStatusDialog(); vm.SelectedProject = Project(BusinessProjectStatusValue.Closed); vm.CanChangeStatus.Should().BeFalse(); vm.SelectedProject = Project(BusinessProjectStatusValue.Cancelled); vm.CanChangeStatus.Should().BeFalse(); }
    [Fact] public async Task Archive_uses_identity_captured_when_dialog_opened() { var c = Company(); var first = Project(id: Guid.NewGuid(), version: 7); var second = Project(); var crud = new FakeProjects { Listed = [first, second] }; var vm = new BusinessProjectsViewModel(crud, new FakeLookup { Items = [c] }, TimeProvider.System); await vm.ReloadCompaniesAsync(); vm.SelectedProject = first; vm.OpenArchiveDialog(); vm.SelectedProject = second; vm.SelectedProject!.Id.Should().Be(first.Id); await vm.ConfirmArchiveAsync(); crud.Archived.Should().Be(new ArchiveBusinessProjectRequest(first.Id, 7)); vm.IsArchiveDialogOpen.Should().BeFalse(); }
    [Fact] public async Task Explicit_all_filter_can_be_restored_after_specific_filter() { var c = Company(); var vm = new BusinessProjectsViewModel(new FakeProjects(), new FakeLookup { Items = [c] }, TimeProvider.System); await vm.ReloadCompaniesAsync(); await vm.SelectStatusFilterAsync(vm.StatusFilters.Single(x => x.Value == BusinessProjectStatusValue.Analysis)); await vm.SelectStatusFilterAsync(vm.StatusFilters[0]); vm.SelectedStatusFilter.Value.Should().BeNull(); }
    [Fact] public async Task Navigate_to_projects_waits_for_company_reload_and_stays_on_failure() { var lookup = new FakeLookup { Gate = new() }; var projects = new BusinessProjectsViewModel(new FakeProjects(), lookup, TimeProvider.System); var workspace = new MainWorkspaceViewModel(new CompaniesViewModel(new FakeCompanies()), projects, Budget(), Actual(), Variance()); var navigation = workspace.NavigateAsync(WorkspaceSection.BusinessProjects); workspace.SelectedSection.Should().Be(WorkspaceSection.Companies); lookup.Gate.SetResult([Company()]); await navigation; workspace.SelectedSection.Should().Be(WorkspaceSection.BusinessProjects); var failedProjects = new BusinessProjectsViewModel(new FakeProjects(), new FakeLookup { Failure = true }, TimeProvider.System); var failed = new MainWorkspaceViewModel(new CompaniesViewModel(new FakeCompanies()), failedProjects, Budget(), Actual(), Variance()); await failed.NavigateAsync(WorkspaceSection.BusinessProjects); failed.SelectedSection.Should().Be(WorkspaceSection.Companies); }
    [Fact] public async Task Explicit_company_and_filter_selection_reload_without_fire_and_forget() { var a = Company(); var b = Company(); var crud = new FakeProjects(); var vm = new BusinessProjectsViewModel(crud, new FakeLookup { Items = [a, b] }, TimeProvider.System); await vm.ReloadCompaniesAsync(); await vm.SelectCompanyAsync(b); vm.SelectedCompany!.Id.Should().Be(b.Id); await vm.SelectStatusFilterAsync(vm.StatusFilters.Single(x => x.Value == BusinessProjectStatusValue.Analysis)); vm.SelectedStatusFilter.Value.Should().Be(BusinessProjectStatusValue.Analysis); await vm.SelectStatusFilterAsync(vm.StatusFilters[0]); vm.SelectedStatusFilter.Value.Should().BeNull(); }
    [Fact] public async Task Editor_and_dialogs_lock_company_project_filter_navigation_and_recovery() { var c = Company(); var p = Project(); var crud = new FakeProjects { Listed = [p], Details = Details(p, BusinessProjectStatusValue.Analysis) }; var vm = new BusinessProjectsViewModel(crud, new FakeLookup { Items = [c] }, TimeProvider.System); var workspace = new MainWorkspaceViewModel(new CompaniesViewModel(new FakeCompanies()), vm, Budget(), Actual(), Variance()); await vm.ReloadCompaniesAsync(); vm.BeginCreate(); vm.CanCancel.Should().BeTrue(); vm.CanSelectCompany.Should().BeFalse(); vm.CanSelectProject.Should().BeFalse(); vm.CanChangeFilter.Should().BeFalse(); workspace.CanNavigate.Should().BeFalse(); workspace.CanOpenRecovery.Should().BeFalse(); vm.CancelEditor(); vm.SelectedProject = p; await vm.OpenStatusDialogAsync(); vm.IsStatusDialogOpen.Should().BeTrue(); vm.CanSelectProject.Should().BeFalse(); workspace.CanOpenRecovery.Should().BeFalse(); vm.CloseStatusDialog(); vm.OpenArchiveDialog(); vm.IsArchiveDialogOpen.Should().BeTrue(); vm.CanSelectCompany.Should().BeFalse(); workspace.CanNavigate.Should().BeFalse(); vm.CloseArchiveDialog(); workspace.CanNavigate.Should().BeTrue(); }
    [Fact] public async Task Capability_notifications_are_raised_when_interaction_state_changes() { var c = Company(); var vm = new BusinessProjectsViewModel(new FakeProjects(), new FakeLookup { Items = [c] }, TimeProvider.System); await vm.ReloadCompaniesAsync(); var names = new List<string?>(); vm.PropertyChanged += (_, e) => names.Add(e.PropertyName); vm.BeginCreate(); names.Should().Contain([nameof(vm.CanCancel), nameof(vm.CanSelectCompany), nameof(vm.CanSelectProject), nameof(vm.CanChangeFilter), nameof(vm.CanNavigate)]); names.Clear(); vm.CancelEditor(); names.Should().Contain(nameof(vm.CanCancel)).And.Contain(nameof(vm.CanNavigate)); }
    [Fact] public async Task Company_selection_commits_company_and_projects_atomically() { var a = Company(); var b = Company(); var old = Project(); var fresh = Project(); var crud = new FakeProjects { ByCompany = new() { [a.Id] = [old], [b.Id] = [fresh] } }; var vm = new BusinessProjectsViewModel(crud, new FakeLookup { Items = [a, b] }, TimeProvider.System); await vm.ReloadCompaniesAsync(); await vm.SelectCompanyAsync(a); var gate = new TaskCompletionSource<IReadOnlyList<BusinessProjectListItem>>(); crud.Gate = gate; var selecting = vm.SelectCompanyAsync(b); vm.SelectedCompany!.Id.Should().Be(a.Id); vm.Projects.Should().Equal(old); gate.SetResult([fresh]); await selecting; vm.SelectedCompany!.Id.Should().Be(b.Id); vm.Projects.Should().Equal(fresh); }
    [Fact] public async Task Failed_or_cancelled_company_selection_preserves_previous_state_and_notifies_binding() { var a = Company(); var b = Company(); var old = Project(); var crud = new FakeProjects { ByCompany = new() { [a.Id] = [old] } }; var vm = new BusinessProjectsViewModel(crud, new FakeLookup { Items = [a, b] }, TimeProvider.System); await vm.ReloadCompaniesAsync(); await vm.SelectCompanyAsync(a); var notified = 0; vm.PropertyChanged += (_, e) => { if (e.PropertyName == nameof(vm.SelectedCompany)) notified++; }; crud.Failure = true; await vm.SelectCompanyAsync(b); vm.SelectedCompany!.Id.Should().Be(a.Id); vm.Projects.Should().Equal(old); notified.Should().BePositive(); crud.Failure = false; crud.Cancel = true; await vm.SelectCompanyAsync(b, new CancellationToken(true)); vm.SelectedCompany!.Id.Should().Be(a.Id); vm.Projects.Should().Equal(old); await vm.SelectCompanyAsync(null); vm.SelectedCompany.Should().BeNull(); vm.Projects.Should().BeEmpty(); }
    [Fact] public async Task Filter_change_is_atomic_and_failed_change_restores_binding() { var c = Company(); var draft = Project(); var analysis = Project(BusinessProjectStatusValue.Analysis); var crud = new FakeProjects { Listed = [draft, analysis] }; var vm = new BusinessProjectsViewModel(crud, new FakeLookup { Items = [c] }, TimeProvider.System); await vm.ReloadCompaniesAsync(); var analysisOption = vm.StatusFilters.Single(x => x.Value == BusinessProjectStatusValue.Analysis); await vm.SelectStatusFilterAsync(analysisOption); vm.Projects.Should().Equal(analysis); var notified = 0; vm.PropertyChanged += (_, e) => { if (e.PropertyName == nameof(vm.SelectedStatusFilter)) notified++; }; crud.Failure = true; await vm.SelectStatusFilterAsync(vm.StatusFilters[0]); vm.SelectedStatusFilter.Should().BeSameAs(analysisOption); vm.Projects.Should().Equal(analysis); notified.Should().BePositive(); }
    [Fact] public async Task Company_archive_captures_identity_and_locks_workspace() { var company = new CompanyListItem(Guid.NewGuid(), "Legal", "Captured", null, "PL", "PLN", CompanyStatusValue.Active, DateTimeOffset.UtcNow, 7); var service = new CapturingCompanies { Listed = [company] }; var companies = new CompaniesViewModel(service); await companies.RefreshAsync(); companies.SelectedCompany = company; var projects = new BusinessProjectsViewModel(new FakeProjects(), new FakeLookup(), TimeProvider.System); var workspace = new MainWorkspaceViewModel(companies, projects, Budget(), Actual(), Variance()); companies.OpenArchiveDialog(); companies.ArchivingCompanyName.Should().Be("Captured"); companies.CanSelectList.Should().BeFalse(); workspace.CanNavigate.Should().BeFalse(); workspace.CanOpenRecovery.Should().BeFalse(); companies.SelectedCompany = null; await companies.ConfirmArchiveAsync(); service.Archived.Should().Be(new ArchiveCompanyRequest(company.Id, 7)); companies.IsArchiveDialogOpen.Should().BeFalse(); workspace.CanNavigate.Should().BeTrue(); }
    [Fact] public async Task Cancelled_filter_keeps_filter_projects_and_selection() { var c = Company(); var selected = Project(BusinessProjectStatusValue.Analysis); var crud = new FakeProjects { Listed = [selected] }; var vm = new BusinessProjectsViewModel(crud, new FakeLookup { Items = [c] }, TimeProvider.System); await vm.ReloadCompaniesAsync(); vm.SelectedProject = selected; var original = vm.SelectedStatusFilter; crud.Cancel = true; await vm.SelectStatusFilterAsync(vm.StatusFilters.Single(x => x.Value == BusinessProjectStatusValue.Analysis), new(true)); vm.SelectedStatusFilter.Should().BeSameAs(original); vm.Projects.Should().Equal(selected); vm.SelectedProject.Should().BeSameAs(selected); }
    [Theory][InlineData(CompanyOperationStatus.ConcurrencyConflict)][InlineData(CompanyOperationStatus.PersistenceFailure)][InlineData(CompanyOperationStatus.Cancelled)] public async Task Company_archive_every_controlled_result_clears_captured_state(CompanyOperationStatus status) { var company = new CompanyListItem(Guid.NewGuid(), "Legal", "Captured", null, "PL", "PLN", CompanyStatusValue.Active, DateTimeOffset.UtcNow, 4); var service = new CapturingCompanies { Listed = [company], Status = status }; var vm = new CompaniesViewModel(service); await vm.RefreshAsync(); vm.SelectedCompany = company; vm.OpenArchiveDialog(); await vm.ConfirmArchiveAsync(); vm.IsArchiveDialogOpen.Should().BeFalse(); vm.ArchivingCompanyName.Should().BeNull(); vm.CanOpenRecovery.Should().BeTrue(); }
    [Fact]
    public async Task Navigate_to_budgeting_reloads_projects_before_switch_and_failure_keeps_companies()
    {
        var lookup = new FakeBudgetLookup { Items = [new(Guid.NewGuid(), "Gym", "PLN", true)] }; var budgeting = new BudgetingViewModel(new FakeBudgeting(), lookup);
        var workspace = new MainWorkspaceViewModel(new CompaniesViewModel(new FakeCompanies()), new BusinessProjectsViewModel(new FakeProjects(), new FakeLookup(), TimeProvider.System), budgeting, Actual(), Variance());
        await workspace.NavigateAsync(WorkspaceSection.Budgeting); lookup.Calls.Should().Be(1); workspace.SelectedSection.Should().Be(WorkspaceSection.Budgeting);
        var failedLookup = new FakeBudgetLookup { Failure = true }; var failed = new MainWorkspaceViewModel(new CompaniesViewModel(new FakeCompanies()), new BusinessProjectsViewModel(new FakeProjects(), new FakeLookup(), TimeProvider.System), new(new FakeBudgeting(), failedLookup), Actual(), Variance());
        await failed.NavigateAsync(WorkspaceSection.Budgeting); failed.SelectedSection.Should().Be(WorkspaceSection.Companies);
    }
    [Fact]
    public async Task Budget_editor_blocks_workspace_navigation_and_recovery_until_cancelled()
    {
        var project = new BudgetProjectInfo(Guid.NewGuid(), "Gym", "PLN", true); var budgeting = new BudgetingViewModel(new FakeBudgeting(), new FakeBudgetLookup { Items = [project] });
        var workspace = new MainWorkspaceViewModel(new CompaniesViewModel(new FakeCompanies()), new BusinessProjectsViewModel(new FakeProjects(), new FakeLookup(), TimeProvider.System), budgeting, Actual(), Variance());
        await budgeting.InitializeAsync(); await budgeting.SelectProjectAsync(project); budgeting.BeginCreateBudget();
        workspace.CanNavigate.Should().BeFalse(); workspace.CanOpenRecovery.Should().BeFalse(); budgeting.CancelBudgetEditor(); workspace.CanNavigate.Should().BeTrue();
    }
    [Fact]
    public async Task Actual_costs_navigation_reloads_before_switch_and_interaction_blocks_workspace()
    {
        var project = new BudgetProjectInfo(Guid.NewGuid(), "Gym", "PLN", true);
        var lookup = new FakeBudgetLookup { Items = [project] };
        var actual = new ActualCostsViewModel(new FakeActualCosts(), lookup, TimeProvider.System);
        var workspace = new MainWorkspaceViewModel(new CompaniesViewModel(new FakeCompanies()), new BusinessProjectsViewModel(new FakeProjects(), new FakeLookup(), TimeProvider.System), Budget(), actual, Variance());
        await workspace.NavigateAsync(WorkspaceSection.ActualCosts);
        lookup.Calls.Should().Be(1); workspace.SelectedSection.Should().Be(WorkspaceSection.ActualCosts);
        await actual.SelectProjectAsync(project); actual.BeginAddCost(); workspace.CanNavigate.Should().BeFalse(); workspace.CanOpenRecovery.Should().BeFalse(); actual.CancelEditor(); workspace.CanNavigate.Should().BeTrue();
    }
    [Fact]
    public async Task Failed_actual_costs_reload_does_not_switch_section()
    {
        var actual = new ActualCostsViewModel(new FakeActualCosts(), new FakeBudgetLookup { Failure = true }, TimeProvider.System);
        var workspace = new MainWorkspaceViewModel(new CompaniesViewModel(new FakeCompanies()), new BusinessProjectsViewModel(new FakeProjects(), new FakeLookup(), TimeProvider.System), Budget(), actual, Variance());
        await workspace.NavigateAsync(WorkspaceSection.ActualCosts);
        workspace.SelectedSection.Should().Be(WorkspaceSection.Companies); actual.LastProjectsReloadSucceeded.Should().BeFalse();
    }
    [Fact]
    public async Task Budget_variance_navigation_reloads_before_switch_and_failure_keeps_section()
    {
        var lookup = new FakeBudgetLookup { Items = [new(Guid.NewGuid(), "Gym", "PLN", true)] };
        var variance = Variance(lookup); var workspace = new MainWorkspaceViewModel(new(new FakeCompanies()), new(new FakeProjects(), new FakeLookup(), TimeProvider.System), Budget(), Actual(), variance);
        await workspace.NavigateAsync(WorkspaceSection.BudgetVariance); lookup.Calls.Should().Be(1); workspace.SelectedSection.Should().Be(WorkspaceSection.BudgetVariance);
        var failed = new MainWorkspaceViewModel(new(new FakeCompanies()), new(new FakeProjects(), new FakeLookup(), TimeProvider.System), Budget(), Actual(), Variance(new() { Failure = true }));
        await failed.NavigateAsync(WorkspaceSection.BudgetVariance); failed.SelectedSection.Should().Be(WorkspaceSection.Companies);
    }
    [Fact]
    public async Task Busy_budget_variance_blocks_global_navigation_and_recovery()
    {
        var project = new BudgetProjectInfo(Guid.NewGuid(), "Gym", "PLN", true); var query = new FakeVariance { BudgetGate = new() }; var variance = Variance(new() { Items = [project] }, query);
        var workspace = new MainWorkspaceViewModel(new(new FakeCompanies()), new(new FakeProjects(), new FakeLookup(), TimeProvider.System), Budget(), Actual(), variance);
        await variance.ReloadProjectsAsync(); var selecting = variance.SelectProjectAsync(project);
        workspace.CanNavigate.Should().BeFalse(); workspace.CanOpenRecovery.Should().BeFalse(); query.BudgetGate.SetResult([]); await selecting; workspace.CanNavigate.Should().BeTrue();
    }
    private sealed class FakeVariance : IBudgetVarianceQueryService { public TaskCompletionSource<IReadOnlyList<BudgetVarianceBudgetItem>>? BudgetGate { get; set; } public Exception? Failure { get; set; } public Task<IReadOnlyList<BudgetVarianceBudgetItem>> ListBudgetsAsync(Guid id, CancellationToken ct) => Failure is null ? BudgetGate?.Task ?? Task.FromResult((IReadOnlyList<BudgetVarianceBudgetItem>)[]) : Task.FromException<IReadOnlyList<BudgetVarianceBudgetItem>>(Failure); public Task<IReadOnlyList<BudgetVarianceVersionItem>> ListVersionsAsync(Guid id, CancellationToken ct) => Task.FromResult((IReadOnlyList<BudgetVarianceVersionItem>)[]); public Task<BudgetVarianceSnapshot?> GetSnapshotAsync(Guid p, Guid b, Guid v, CancellationToken ct) => Task.FromResult<BudgetVarianceSnapshot?>(null); }
    private sealed class FakeBudgetLookup : IBudgetingProjectLookup { public IReadOnlyList<BudgetProjectInfo> Items { get; set; } = []; public bool Failure { get; set; } public int Calls { get; private set; } public Task<BudgetProjectInfo?> GetAsync(Guid id, CancellationToken ct) => Task.FromResult(Items.FirstOrDefault(x => x.Id == id)); public Task<IReadOnlyList<BudgetProjectInfo>> ListAvailableAsync(CancellationToken ct) { Calls++; return Failure ? Task.FromException<IReadOnlyList<BudgetProjectInfo>>(new BudgetingProjectLookupException("x", new Exception())) : Task.FromResult(Items); } }
    private sealed class FakeActualCosts : IActualCostsCrudService { public Task<IReadOnlyList<ActualCostItem>> ListAsync(Guid id, CancellationToken ct) => Task.FromResult((IReadOnlyList<ActualCostItem>)[]); public Task<ActualCostItem?> GetAsync(Guid id, CancellationToken ct) => Task.FromResult<ActualCostItem?>(null); public Task<ActualCostResult<ActualCostItem>> CreateAsync(Guid p, BusinessOS.Modules.Budgeting.Domain.ActualCostKind k, string n, decimal a, string c, DateOnly d, string? note, CancellationToken ct) => throw new NotSupportedException(); public Task<ActualCostResult<ActualCostItem>> UpdateAsync(Guid id, long v, BusinessOS.Modules.Budgeting.Domain.ActualCostKind k, string n, decimal a, string c, DateOnly d, string? note, CancellationToken ct) => throw new NotSupportedException(); public Task<ActualCostResult> ArchiveAsync(Guid id, long v, CancellationToken ct) => throw new NotSupportedException(); }
    private sealed class FakeBudgeting : IBudgetingCrudService { public Task<IReadOnlyList<BudgetItem>> ListBudgetsAsync(Guid id, CancellationToken ct) => Task.FromResult((IReadOnlyList<BudgetItem>)[]); public Task<BudgetItem?> GetBudgetAsync(Guid id, CancellationToken ct) => Task.FromResult<BudgetItem?>(null); public Task<BudgetingResult<BudgetItem>> CreateBudgetAsync(Guid id, string n, CancellationToken ct) => throw new NotSupportedException(); public Task<BudgetingResult<BudgetItem>> RenameBudgetAsync(Guid id, long v, string n, CancellationToken ct) => throw new NotSupportedException(); public Task<BudgetingResult<BudgetItem>> ActivateBudgetAsync(Guid id, long v, CancellationToken ct) => throw new NotSupportedException(); public Task<BudgetingResult> ArchiveBudgetAsync(Guid id, long v, CancellationToken ct) => throw new NotSupportedException(); public Task<BudgetingResult<BudgetVersionItem>> CreateInitialVersionAsync(Guid id, long v, string? n, CancellationToken ct) => throw new NotSupportedException(); public Task<BudgetingResult<BudgetVersionItem>> CreateNextVersionAsync(Guid id, long v, string? n, CancellationToken ct) => throw new NotSupportedException(); public Task<BudgetVersionItem?> GetVersionAsync(Guid id, CancellationToken ct) => throw new NotSupportedException(); public Task<IReadOnlyList<BudgetVersionItem>> ListVersionsAsync(Guid id, CancellationToken ct) => Task.FromResult((IReadOnlyList<BudgetVersionItem>)[]); public Task<BudgetingResult<BudgetLineItem>> AddLineAsync(Guid id, BusinessOS.Modules.Budgeting.Domain.BudgetLineKind k, string n, decimal a, string c, int o, string? note, CancellationToken ct) => throw new NotSupportedException(); public Task<BudgetingResult<BudgetLineItem>> UpdateLineAsync(Guid id, BusinessOS.Modules.Budgeting.Domain.BudgetLineKind k, string n, decimal a, string c, int o, string? note, CancellationToken ct) => throw new NotSupportedException(); public Task<BudgetingResult> RemoveLineAsync(Guid id, CancellationToken ct) => throw new NotSupportedException(); }
    private sealed class FakeLookup : ICompaniesLookupService { public IReadOnlyList<CompanyLookupItem> Items { get; set; } = []; public TaskCompletionSource<IReadOnlyList<CompanyLookupItem>>? Gate { get; set; } public bool Failure { get; set; } public Task<IReadOnlyList<CompanyLookupItem>> ListActiveAsync(CancellationToken ct) { if (Failure) throw new InvalidOperationException(); return Gate?.Task ?? Task.FromResult(Items); } public Task<CompanyLookupItem?> GetActiveAsync(Guid id, CancellationToken ct) => Task.FromResult(Items.FirstOrDefault(x => x.Id == id)); }
    private sealed class FakeProjects : IBusinessProjectsCrudService { public IReadOnlyList<BusinessProjectListItem> Listed { get; set; } = []; public Dictionary<Guid, IReadOnlyList<BusinessProjectListItem>> ByCompany { get; set; } = []; public TaskCompletionSource<IReadOnlyList<BusinessProjectListItem>>? Gate { get; set; } public bool Failure { get; set; } public bool Cancel { get; set; } public BusinessProjectDetails? Details { get; set; } public ArchiveBusinessProjectRequest? Archived { get; set; } public Task<IReadOnlyList<BusinessProjectListItem>> ListAsync(Guid id, BusinessProjectStatusValue? status, CancellationToken ct) { if (Cancel) throw new OperationCanceledException(ct); if (Failure) throw new BusinessProjectsReadExceptionForTests(); if (Gate is { } gate) return gate.Task; var source = ByCompany.TryGetValue(id, out var scoped) ? scoped : Listed; return Task.FromResult((IReadOnlyList<BusinessProjectListItem>)source.Where(x => status is null || x.Status == status).ToArray()); } public Task<BusinessProjectDetails?> GetAsync(Guid id, CancellationToken ct) => Task.FromResult(Details); public Task<BusinessProjectOperationResult<BusinessProjectDetails>> CreateAsync(CreateBusinessProjectRequest r, CancellationToken ct) => Task.FromResult(new BusinessProjectOperationResult<BusinessProjectDetails>(BusinessProjectOperationStatus.Success, "ok", new Dictionary<string, string[]>(), Details)); public Task<BusinessProjectOperationResult<BusinessProjectDetails>> UpdateAsync(UpdateBusinessProjectRequest r, CancellationToken ct) => CreateAsync(default!, ct); public Task<BusinessProjectOperationResult<BusinessProjectDetails>> ChangeStatusAsync(ChangeBusinessProjectStatusRequest r, CancellationToken ct) => CreateAsync(default!, ct); public Task<BusinessProjectOperationResult> ArchiveAsync(ArchiveBusinessProjectRequest r, CancellationToken ct) { Archived = r; return Task.FromResult(new BusinessProjectOperationResult(BusinessProjectOperationStatus.Success, "ok", new Dictionary<string, string[]>())); } public Task<bool> HasActiveProjectsAsync(Guid id, CancellationToken ct) => Task.FromResult(false); }
    private sealed class BusinessProjectsReadExceptionForTests : Exception { }
    private sealed class CapturingCompanies : ICompaniesCrudService { public IReadOnlyList<CompanyListItem> Listed { get; set; } = []; public CompanyOperationStatus Status { get; set; } = CompanyOperationStatus.Success; public ArchiveCompanyRequest? Archived { get; set; } public Task<IReadOnlyList<CompanyListItem>> ListAsync(CancellationToken ct) => Task.FromResult(Listed); public Task<CompanyDetails?> GetAsync(Guid id, CancellationToken ct) => Task.FromResult<CompanyDetails?>(null); public Task<CompanyOperationResult<CompanyDetails>> CreateAsync(CreateCompanyRequest r, CancellationToken ct) => throw new NotSupportedException(); public Task<CompanyOperationResult<CompanyDetails>> UpdateAsync(UpdateCompanyRequest r, CancellationToken ct) => throw new NotSupportedException(); public Task<CompanyOperationResult> ArchiveAsync(ArchiveCompanyRequest r, CancellationToken ct) { Archived = r; return Task.FromResult(new CompanyOperationResult(Status, "ok", new Dictionary<string, string[]>())); } }
    private sealed class FakeCompanies : ICompaniesCrudService { public Task<IReadOnlyList<CompanyListItem>> ListAsync(CancellationToken ct) => Task.FromResult((IReadOnlyList<CompanyListItem>)[]); public Task<CompanyDetails?> GetAsync(Guid id, CancellationToken ct) => Task.FromResult<CompanyDetails?>(null); public Task<CompanyOperationResult<CompanyDetails>> CreateAsync(CreateCompanyRequest r, CancellationToken ct) => throw new NotSupportedException(); public Task<CompanyOperationResult<CompanyDetails>> UpdateAsync(UpdateCompanyRequest r, CancellationToken ct) => throw new NotSupportedException(); public Task<CompanyOperationResult> ArchiveAsync(ArchiveCompanyRequest r, CancellationToken ct) => throw new NotSupportedException(); }
}
