using BusinessOS.BuildingBlocks.Domain.Ids;
using BusinessOS.BuildingBlocks.Domain.Primitives;
using BusinessOS.Modules.Budgeting.Domain;
using Microsoft.Extensions.DependencyInjection;

namespace BusinessOS.Modules.Budgeting.Application;

public enum BudgetingOperationStatus { Success, ValidationFailure, NotFound, ConcurrencyConflict, ProjectUnavailable, Archived, DuplicateName, PersistenceFailure, Cancelled }
public sealed record BudgetingResult(BudgetingOperationStatus Status, string SafeMessage);
public sealed record BudgetingResult<T>(BudgetingOperationStatus Status, string SafeMessage, T? Value);
public sealed record BudgetVersionCreationResult(BudgetingOperationStatus Status, BudgetVersion? Version);
public sealed record BudgetItem(Guid Id, Guid ProjectId, string Name, BudgetStatus Status, DateTimeOffset UpdatedAtUtc, long Version, int LatestVersion);
public sealed record BudgetVersionItem(Guid Id, Guid BudgetId, int Number, DateTimeOffset CreatedAtUtc, string? Note, IReadOnlyList<BudgetLineItem> Lines);
public sealed record BudgetLineItem(Guid Id, Guid VersionId, BudgetLineKind Kind, string Name, decimal Amount, string Currency, int SortOrder, string? Note);
public sealed record BudgetProjectInfo(Guid Id, string Name, string BaseCurrency, bool Available);
public interface IBudgetingProjectLookup { Task<BudgetProjectInfo?> GetAsync(Guid projectId, CancellationToken cancellationToken); Task<IReadOnlyList<BudgetProjectInfo>> ListAvailableAsync(CancellationToken cancellationToken); }
public sealed class BudgetingProjectLookupException(string message, Exception inner) : Exception(message, inner);
public sealed class BudgetingReadException(Exception inner) : Exception("Budgeting data could not be read.", inner);
public interface IBudgetingStore
{
    Task<IReadOnlyList<Budget>> ListBudgetsAsync(BusinessProjectId projectId, CancellationToken ct); Task<Budget?> GetBudgetAsync(BudgetId id, bool tracked, CancellationToken ct); Task<bool> NameExistsAsync(BusinessProjectId projectId, string normalizedName, BudgetId? except, CancellationToken ct); Task AddBudgetAsync(Budget budget, CancellationToken ct); Task<BudgetingOperationStatus> SaveAsync(CancellationToken ct); Task<IReadOnlyList<BudgetVersion>> ListVersionsAsync(BudgetId id, CancellationToken ct); Task<BudgetVersion?> GetVersionAsync(BudgetVersionId id, CancellationToken ct); Task<IReadOnlyList<BudgetLine>> ListLinesAsync(BudgetVersionId id, CancellationToken ct); Task AddVersionAsync(BudgetVersion version, CancellationToken ct); Task AddLineAsync(BudgetLine line, CancellationToken ct); Task<BudgetLine?> GetLineAsync(Guid id, bool tracked, CancellationToken ct); Task RemoveLineAsync(BudgetLine line, CancellationToken ct); Task<BudgetVersionCreationResult> CreateInitialVersionAsync(BudgetId id, long expectedVersion, string? note, DateTimeOffset now, CancellationToken ct); Task<BudgetVersionCreationResult> CreateNextVersionAsync(Budget budget, long expectedVersion, string? note, DateTimeOffset now, CancellationToken ct); Task ResetTrackingAsync();
}
public interface IBudgetingCrudService
{
    Task<IReadOnlyList<BudgetItem>> ListBudgetsAsync(Guid projectId, CancellationToken ct); Task<BudgetItem?> GetBudgetAsync(Guid budgetId, CancellationToken ct); Task<BudgetingResult<BudgetItem>> CreateBudgetAsync(Guid projectId, string name, CancellationToken ct); Task<BudgetingResult<BudgetItem>> RenameBudgetAsync(Guid id, long expectedVersion, string name, CancellationToken ct); Task<BudgetingResult<BudgetItem>> ActivateBudgetAsync(Guid id, long expectedVersion, CancellationToken ct); Task<BudgetingResult> ArchiveBudgetAsync(Guid id, long expectedVersion, CancellationToken ct); Task<BudgetingResult<BudgetVersionItem>> CreateInitialVersionAsync(Guid budgetId, long expectedVersion, string? note, CancellationToken ct); Task<BudgetingResult<BudgetVersionItem>> CreateNextVersionAsync(Guid budgetId, long expectedVersion, string? note, CancellationToken ct); Task<BudgetVersionItem?> GetVersionAsync(Guid id, CancellationToken ct); Task<IReadOnlyList<BudgetVersionItem>> ListVersionsAsync(Guid budgetId, CancellationToken ct); Task<BudgetingResult<BudgetLineItem>> AddLineAsync(Guid versionId, BudgetLineKind kind, string name, decimal amount, string currency, int sortOrder, string? note, CancellationToken ct); Task<BudgetingResult<BudgetLineItem>> UpdateLineAsync(Guid id, BudgetLineKind kind, string name, decimal amount, string currency, int sortOrder, string? note, CancellationToken ct); Task<BudgetingResult> RemoveLineAsync(Guid id, CancellationToken ct);
}
public static class BudgetingServices { public static IServiceCollection AddBudgetingModule(this IServiceCollection services) { services.AddTransient<IBudgetingCrudService, BudgetingCrudService>(); services.AddTransient<IActualCostsCrudService, ActualCostsCrudService>(); return services; } }

internal sealed class BudgetingCrudService(IBudgetingStore store, IBudgetingProjectLookup projects, TimeProvider clock) : IBudgetingCrudService
{
    public Task<IReadOnlyList<BudgetItem>> ListBudgetsAsync(Guid projectId, CancellationToken ct) => ReadAsync(() => MapBudgets(store.ListBudgetsAsync(new(projectId), ct), ct), ct);
    public Task<BudgetItem?> GetBudgetAsync(Guid id, CancellationToken ct) => ReadAsync(async () => { var b = await store.GetBudgetAsync(new(id), false, ct); return b is null ? null : await Map(b, ct); }, ct);
    public Task<BudgetingResult<BudgetItem>> CreateBudgetAsync(Guid p, string n, CancellationToken ct) => Guard(async () => { var project = await GetAvailableProjectAsync(new(p), ct); if (project is null) return Fail<BudgetItem>(BudgetingOperationStatus.ProjectUnavailable, "Projekt nie jest dostępny."); var b = Budget.Create(new(p), n, clock.GetUtcNow()); if (await store.NameExistsAsync(b.ProjectId, b.NormalizedName, null, ct)) return Fail<BudgetItem>(BudgetingOperationStatus.DuplicateName, "Budżet o tej nazwie już istnieje."); await store.AddBudgetAsync(b, ct); return await Saved(b, "Budżet został utworzony.", ct); }, ct);
    public Task<BudgetingResult<BudgetItem>> RenameBudgetAsync(Guid id, long v, string n, CancellationToken ct) => Mutate(id, v, async b => { if (await GetAvailableProjectAsync(b.ProjectId, ct) is null) return Fail<BudgetItem>(BudgetingOperationStatus.ProjectUnavailable, "Projekt nie jest dostępny."); var name = Budget.NormalizeName(n); if (await store.NameExistsAsync(b.ProjectId, Budget.NormalizeKey(name), b.Id, ct)) return Fail<BudgetItem>(BudgetingOperationStatus.DuplicateName, "Budżet o tej nazwie już istnieje."); b.Rename(name, clock.GetUtcNow()); return await Saved(b, "Nazwa została zmieniona.", ct); }, ct);
    public Task<BudgetingResult<BudgetItem>> ActivateBudgetAsync(Guid id, long v, CancellationToken ct) => Mutate(id, v, async b => { if (await GetAvailableProjectAsync(b.ProjectId, ct) is null) return Fail<BudgetItem>(BudgetingOperationStatus.ProjectUnavailable, "Projekt nie jest dostępny."); var versions = await store.ListVersionsAsync(b.Id, ct); var populated = versions.Count > 0 && (await store.ListLinesAsync(versions.MaxBy(x => x.Number)!.Id, ct)).Count > 0; b.Activate(populated, clock.GetUtcNow()); return await Saved(b, "Budżet został aktywowany.", ct); }, ct);
    public async Task<BudgetingResult> ArchiveBudgetAsync(Guid id, long v, CancellationToken ct) { var result = await Mutate(id, v, async b => { b.Archive(clock.GetUtcNow()); return await Saved(b, "Budżet został zarchiwizowany.", ct); }, ct); return new(result.Status, result.SafeMessage); }
    public Task<BudgetingResult<BudgetVersionItem>> CreateInitialVersionAsync(Guid id, long v, string? note, CancellationToken ct) => Guard(async () => { var b = await store.GetBudgetAsync(new(id), false, ct); if (b is null) return Fail<BudgetVersionItem>(BudgetingOperationStatus.NotFound, "Nie znaleziono budżetu."); var project = await GetAvailableProjectAsync(b.ProjectId, ct); if (project is null) return Fail<BudgetVersionItem>(BudgetingOperationStatus.ProjectUnavailable, "Projekt nie jest dostępny."); var created = await store.CreateInitialVersionAsync(b.Id, v, note, clock.GetUtcNow(), ct); if (created.Status != BudgetingOperationStatus.Success || created.Version is null) return Fail<BudgetVersionItem>(created.Status, "Nie udało się utworzyć wersji."); return new(created.Status, "Utworzono wersję 1.", await Map(created.Version, ct)); }, ct);
    public Task<BudgetingResult<BudgetVersionItem>> CreateNextVersionAsync(Guid id, long v, string? note, CancellationToken ct) => Guard(async () => { var b = await store.GetBudgetAsync(new(id), false, ct); if (b is null) return Fail<BudgetVersionItem>(BudgetingOperationStatus.NotFound, "Nie znaleziono budżetu."); var project = await GetAvailableProjectAsync(b.ProjectId, ct); if (project is null) return Fail<BudgetVersionItem>(BudgetingOperationStatus.ProjectUnavailable, "Projekt nie jest dostępny."); var created = await store.CreateNextVersionAsync(b, v, note, clock.GetUtcNow(), ct); if (created.Status != BudgetingOperationStatus.Success || created.Version is null) return Fail<BudgetVersionItem>(created.Status, "Nie udało się utworzyć kolejnej wersji."); return new(created.Status, "Utworzono kolejną wersję.", await Map(created.Version, ct)); }, ct);
    public Task<BudgetVersionItem?> GetVersionAsync(Guid id, CancellationToken ct) => ReadAsync(async () => { var v = await store.GetVersionAsync(new(id), ct); return v is null ? null : await Map(v, ct); }, ct);
    public Task<IReadOnlyList<BudgetVersionItem>> ListVersionsAsync(Guid id, CancellationToken ct) => ReadAsync(async () => { var result = new List<BudgetVersionItem>(); foreach (var v in await store.ListVersionsAsync(new(id), ct)) result.Add(await Map(v, ct)); return (IReadOnlyList<BudgetVersionItem>)result; }, ct);
    public Task<BudgetingResult<BudgetLineItem>> AddLineAsync(Guid version, BudgetLineKind kind, string name, decimal amount, string currency, int order, string? note, CancellationToken ct) => Guard(async () => { var access = await Editable(new(version), currency, ct); if (access.Error is not null) return Fail<BudgetLineItem>(access.Error.Value, access.Message!); var l = BudgetLine.Create(new(version), kind, name, new(amount, new(currency.Trim().ToUpperInvariant())), order, note); await store.AddLineAsync(l, ct); var s = await store.SaveAsync(ct); return s == BudgetingOperationStatus.Success ? new(s, "Linia została dodana.", Map(l)) : Fail<BudgetLineItem>(s, "Nie udało się zapisać linii."); }, ct);
    public Task<BudgetingResult<BudgetLineItem>> UpdateLineAsync(Guid id, BudgetLineKind kind, string name, decimal amount, string currency, int order, string? note, CancellationToken ct) => Guard(async () => { var l = await store.GetLineAsync(id, true, ct); if (l is null) return Fail<BudgetLineItem>(BudgetingOperationStatus.NotFound, "Nie znaleziono linii."); var access = await Editable(l.VersionId, currency, ct); if (access.Error is not null) return Fail<BudgetLineItem>(access.Error.Value, access.Message!); l.Update(kind, name, new(amount, new(currency.Trim().ToUpperInvariant())), order, note); var s = await store.SaveAsync(ct); return s == BudgetingOperationStatus.Success ? new(s, "Linia została zmieniona.", Map(l)) : Fail<BudgetLineItem>(s, "Nie udało się zapisać linii."); }, ct);
    public async Task<BudgetingResult> RemoveLineAsync(Guid id, CancellationToken ct) { var r = await Guard(async () => { var l = await store.GetLineAsync(id, true, ct); if (l is null) return Fail<BudgetLineItem>(BudgetingOperationStatus.NotFound, "Nie znaleziono linii."); var access = await Editable(l.VersionId, l.Amount.Currency.Value, ct); if (access.Error is not null) return Fail<BudgetLineItem>(access.Error.Value, access.Message!); await store.RemoveLineAsync(l, ct); var s = await store.SaveAsync(ct); return new BudgetingResult<BudgetLineItem>(s, s == BudgetingOperationStatus.Success ? "Linia została usunięta." : "Nie udało się usunąć linii.", null); }, ct); return new(r.Status, r.SafeMessage); }
    private async Task<BudgetProjectInfo?> GetAvailableProjectAsync(BusinessProjectId id, CancellationToken ct) { var project = await projects.GetAsync(id.Value, ct); return project is { Available: true } ? project : null; }
    private async Task<(BudgetingOperationStatus? Error, string? Message)> Editable(BudgetVersionId id, string currency, CancellationToken ct) { var v = await store.GetVersionAsync(id, ct); if (v is null) return (BudgetingOperationStatus.NotFound, "Nie znaleziono wersji."); var b = await store.GetBudgetAsync(v.BudgetId, false, ct); if (b is null) return (BudgetingOperationStatus.NotFound, "Nie znaleziono budżetu."); if (b.Status == BudgetStatus.Archived) return (BudgetingOperationStatus.Archived, "Budżet jest zarchiwizowany."); if (b.Status != BudgetStatus.Draft || (await store.ListVersionsAsync(b.Id, ct)).Max(x => x.Number) != v.Number) return (BudgetingOperationStatus.ValidationFailure, "Ta wersja jest tylko do odczytu."); var p = await projects.GetAsync(b.ProjectId.Value, ct); if (p is not { Available: true }) return (BudgetingOperationStatus.ProjectUnavailable, "Projekt nie jest dostępny."); return !string.Equals(p.BaseCurrency, currency.Trim(), StringComparison.OrdinalIgnoreCase) ? (BudgetingOperationStatus.ValidationFailure, "Waluta linii musi być walutą bazową projektu.") : (null, null); }
    private Task<BudgetingResult<BudgetItem>> Mutate(Guid id, long version, Func<Budget, Task<BudgetingResult<BudgetItem>>> action, CancellationToken ct) => Guard(async () => { var b = await store.GetBudgetAsync(new(id), true, ct); if (b is null) return Fail<BudgetItem>(BudgetingOperationStatus.NotFound, "Nie znaleziono budżetu."); if (b.Status == BudgetStatus.Archived) return Fail<BudgetItem>(BudgetingOperationStatus.Archived, "Budżet jest zarchiwizowany."); return b.Version != version ? Fail<BudgetItem>(BudgetingOperationStatus.ConcurrencyConflict, "Budżet został zmieniony.") : await action(b); }, ct);
    private async Task<BudgetingResult<BudgetItem>> Saved(Budget b, string message, CancellationToken ct) { var s = await store.SaveAsync(ct); return s == BudgetingOperationStatus.Success ? new(s, message, await Map(b, ct)) : Fail<BudgetItem>(s, "Nie udało się zapisać budżetu."); }
    private async Task<T> Guard<T>(Func<Task<T>> work, CancellationToken ct) where T : class { try { ct.ThrowIfCancellationRequested(); return await work(); } catch (OperationCanceledException) when (ct.IsCancellationRequested) { return (T)Activator.CreateInstance(typeof(T), BudgetingOperationStatus.Cancelled, "Operacja została anulowana.", null)!; } catch (ArgumentException) { return (T)Activator.CreateInstance(typeof(T), BudgetingOperationStatus.ValidationFailure, "Popraw wskazane dane.", null)!; } catch (InvalidOperationException) { return (T)Activator.CreateInstance(typeof(T), BudgetingOperationStatus.ValidationFailure, "Operacja jest niedozwolona.", null)!; } catch (Exception e) when (e is BudgetingPersistenceException or BudgetingProjectLookupException) { return (T)Activator.CreateInstance(typeof(T), BudgetingOperationStatus.PersistenceFailure, "Nie udało się wykonać operacji.", null)!; } finally { await store.ResetTrackingAsync(); } }
    private static BudgetingResult<T> Fail<T>(BudgetingOperationStatus s, string m) => new(s, m, default);
    private async Task<IReadOnlyList<BudgetItem>> MapBudgets(Task<IReadOnlyList<Budget>> source, CancellationToken ct) { var r = new List<BudgetItem>(); foreach (var b in await source) r.Add(await Map(b, ct)); return r; }
    private static async Task<T> ReadAsync<T>(Func<Task<T>> read, CancellationToken ct) { try { return await read(); } catch (OperationCanceledException) when (ct.IsCancellationRequested) { throw; } catch (Exception e) when (e is BudgetingPersistenceException or BudgetingProjectLookupException) { throw new BudgetingReadException(e); } }
    private async Task<BudgetItem> Map(Budget b, CancellationToken ct) => new(b.Id.Value, b.ProjectId.Value, b.Name, b.Status, b.UpdatedAtUtc, b.Version, (await store.ListVersionsAsync(b.Id, ct)).Select(x => x.Number).DefaultIfEmpty().Max());
    private async Task<BudgetVersionItem> Map(BudgetVersion v, CancellationToken ct) => new(v.Id.Value, v.BudgetId.Value, v.Number, v.CreatedAtUtc, v.Note, (await store.ListLinesAsync(v.Id, ct)).Select(Map).ToArray());
    private static BudgetLineItem Map(BudgetLine l) => new(l.Id, l.VersionId.Value, l.Kind, l.Name, l.Amount.Amount, l.Amount.Currency.Value, l.SortOrder, l.Note);
}
public sealed class BudgetingPersistenceException(string message, Exception inner) : Exception(message, inner);
